# Generated by Django 2.0.5 on 2018-09-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("user", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="location",
            field=models.UUIDField(blank=True, null=True),
        )
    ]
