# Generated by Django 2.1.2 on 2018-10-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("user", "0002_auto_20180927_1027")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="internal",
            field=models.BooleanField(default=False),
        )
    ]
