# Generated by Django 2.2.3 on 2019-08-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sso_user_id',
            field=models.UUIDField(help_text='Staff SSO UUID for reference', null=True),
        ),
    ]
