# Generated by Django 2.2.11 on 2020-05-04 07:33

from django.db import migrations


def convert_watchlists_to_saved_searches(apps, schema_editor):
    Profile = apps.get_model("user", "Profile")
    SavedSearch = apps.get_model("user", "SavedSearch")

    for profile in Profile.objects.filter(user_profile__isnull=False):
        if "watchList" in profile.user_profile:
            watchlists = profile.user_profile["watchList"].get("lists", [])
            for watchlist in watchlists:
                if watchlist.get("name") and "filters" in watchlist:
                    SavedSearch.objects.create(
                        user=profile.user,
                        name=watchlist.get("name"),
                        filters=watchlist.get("filters"),
                    )


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_saved_searches'),
    ]

    operations = [
        migrations.RunPython(
            convert_watchlists_to_saved_searches,
            reverse_code=migrations.RunPython.noop
        ),
    ]
