# Generated by Django 2.2.11 on 2020-05-20 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_clean_filters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedsearch',
            options={'ordering': ('name',)},
        ),
    ]
