# Generated by Django 2.2.13 on 2020-06-19 09:41

from django.db import migrations


def add_permission_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.create(name="Sifter")
    Group.objects.create(name="Editor")
    Group.objects.create(name="Publisher")
    Group.objects.create(name="Administrator")


def delete_permission_groups(apps, schema_editor):
    Group.objects.delete(name__in=("Sifter", "Editor", "Publisher", "Administrator"))


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_last_notified_fields'),
    ]

    operations = [
        migrations.RunPython(add_permission_groups, reverse_code=delete_permission_groups),
    ]
