# Generated by Django 2.2.13 on 2020-06-24 14:20

from django.db import migrations


def create_permissions(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    User = apps.get_model("auth", "User")

    user_content_type = ContentType.objects.get_for_model(User)
    Permission.objects.create(
        codename="list_users",
        name='Can list users',
        content_type=user_content_type,
    )


def assign_permissions(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    Group = apps.get_model("auth", "Group")
    change_user_permission = Permission.objects.get(codename="change_user")
    list_users_permission = Permission.objects.get(codename="list_users")

    administrator_group = Group.objects.get(name="Administrator")
    administrator_group.permissions.add(change_user_permission)
    administrator_group.permissions.add(list_users_permission)


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_add_permission_groups'),
    ]

    operations = [
        migrations.RunPython(create_permissions, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(assign_permissions, reverse_code=migrations.RunPython.noop),
    ]
