# Generated by Django 2.2.13 on 2020-06-30 13:44

from django.db import migrations


def assign_permissions(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    Group = apps.get_model("auth", "Group")

    change_barrier_public_eligibility = Permission.objects.get(codename="change_barrier_public_eligibility")
    change_publicbarrier = Permission.objects.get(codename="change_publicbarrier")
    mark_barrier_as_ready_for_publishing = Permission.objects.get(codename="mark_barrier_as_ready_for_publishing")
    publish_barrier = Permission.objects.get(codename="publish_barrier")

    administrator_group = Group.objects.get(name="Administrator")
    administrator_group.permissions.add(
        change_barrier_public_eligibility,
        change_publicbarrier,
        mark_barrier_as_ready_for_publishing,
        publish_barrier,
    )

    sifter_group = Group.objects.get(name="Sifter")
    sifter_group.permissions.add(change_barrier_public_eligibility)

    editor_group = Group.objects.get(name="Editor")
    editor_group.permissions.add(
        change_barrier_public_eligibility,
        change_publicbarrier,
        mark_barrier_as_ready_for_publishing,
    )

    publisher_group = Group.objects.get(name="Publisher")
    publisher_group.permissions.add(
        change_barrier_public_eligibility,
        change_publicbarrier,
        mark_barrier_as_ready_for_publishing,
        publish_barrier,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0001_initial'),
        ('barriers', '0067_public_barrier_permissions'),
        ('user', '0014_assign_permissions'),
    ]

    operations = [
        migrations.RunPython(assign_permissions, reverse_code=migrations.RunPython.noop),
    ]
