# Generated by Django 3.1.7 on 2021-03-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_analyst_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybarrierssavedsearch',
            name='notify_about_additions',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mybarrierssavedsearch',
            name='notify_about_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='notify_about_additions',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='notify_about_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='teambarrierssavedsearch',
            name='notify_about_additions',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='teambarrierssavedsearch',
            name='notify_about_updates',
            field=models.BooleanField(default=True),
        ),
    ]
