# Generated by Django 3.1.7 on 2021-03-09 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20210305_1028'),
        ('user', '0020_auto_20210309_1146'),
    ]

    operations = [
    ]
