# Generated by Django 3.1.8 on 2021-05-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_merge_20210309_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sso_email_user_id',
            field=models.CharField(blank=True, help_text='Canonical Staff SSO UUID for reference', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sso_user_id',
            field=models.UUIDField(blank=True, help_text='Legacy Staff SSO UUID for reference', null=True),
        ),
    ]
