# Generated by Django 3.2.7 on 2021-11-26 08:30

from django.db import migrations


# Migration that creates a user group called "Download approved user"
def create_barrier_search_download_approved_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.create(name="Download approved user")

    # create a "download_barrier" Permission and add it to the group
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Barrier = apps.get_model("barriers", "Barrier")
    barrier_content_type = ContentType.objects.get_for_model(Barrier)
    download_barriers_permission, created = Permission.objects.get_or_create(
        codename="download_barriers",
        defaults={
            "name": "Can download barriers",
            "content_type": barrier_content_type,
        },
    )
    group = Group.objects.get(name="Download approved user")
    group.permissions.add(download_barriers_permission)


def undo_create_barrier_search_download_approved_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name="Download approved user").delete()

    # remove "download_barriers" Permission
    Permission = apps.get_model("auth", "Permission")
    permission = Permission.objects.get(codename="download_barriers")
    permission.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0022_auto_20210510_1019"),
        ("barriers", "0113_alter_barrier_options"),
    ]

    operations = [
        migrations.RunPython(
            create_barrier_search_download_approved_group,
            undo_create_barrier_search_download_approved_group,
        ),
    ]
