# Generated by Django 3.2.12 on 2022-05-17 14:00

from django.db import migrations


def create_top_priority_barrier_permission_group(app, shcema_editor):
    # create PB100 approver group and add permission
    Permission = app.get_model("auth", "Permission")
    Group = app.get_model("auth", "Group")

    pb100_group, created = Group.objects.get_or_create(
        name="PB100 barrier approver",
    )

    # get set_topprioritybarrier permission
    pb100_permission = Permission.objects.get(codename="set_topprioritybarrier")

    pb100_group.permissions.add(pb100_permission)


def reverse_create_top_priority_barrier_permission_group(app, shcema_editor):
    # delete the created group
    Group = app.get_model("auth", "Group")
    Group.objects.get(name="PB100 barrier approver").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0026_add_top_barrier_permission"),
    ]

    operations = [
        migrations.RunPython(
            code=create_top_priority_barrier_permission_group,
            reverse_code=reverse_create_top_priority_barrier_permission_group,
        )
    ]
