# Generated by Django 3.2.15 on 2022-10-17 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0028_add_regional_lead_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActvitiyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.TextField(choices=[('USER_LOGGED_IN', 'User logged in'), ('USER_LOGGED_OUT', 'User logged out'), ('BARRIRE_CSV_EXPORT', 'Barrier CSV export'), ('START_DAY_ACTIVITY', 'Start day activity'), ('END_DAY_ACTIVITY', 'End day activity')])),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('event_description', models.TextField(help_text='A human readable description of the event')),
                ('event_data', models.JSONField(blank=True, help_text='Field for extra event based data that is not covered by other fields', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-event_time',),
            },
        ),
    ]
