# Generated by Django 3.2.16 on 2023-02-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_profile_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractvitiylog',
            name='event_type',
            field=models.TextField(choices=[('USER_LOGGED_IN', 'User logged in'), ('BARRIER_CSV_DOWNLOAD', 'Barrier CSV download'), ('START_DAY_ACTIVITY', 'Start day activity'), ('END_DAY_ACTIVITY', 'End day activity')]),
        ),
    ]
