# Generated by Django 4.2.11 on 2024-10-18 11:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0049_initial_policy_teams"),
        ("user", "0036_publishing_permissions_revision"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="organisations",
            field=models.ManyToManyField(
                help_text="Organisations that are related to the barrier",
                to="metadata.organisation",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="policy_teams",
            field=models.ManyToManyField(to="metadata.policyteam"),
        ),
        migrations.AddField(
            model_name="profile",
            name="sectors",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(), blank=True, default=list, size=None
            ),
        ),
    ]
