# Generated by Django 4.2.11 on 2024-10-21 14:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0049_initial_policy_teams"),
        ("user", "0037_profile_organisations_profile_policy_teams_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="organisations",
            field=models.ManyToManyField(
                help_text="Organisations that the user is interested in",
                to="metadata.organisation",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="policy_teams",
            field=models.ManyToManyField(
                help_text="Policy teams that the user is interested in",
                to="metadata.policyteam",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="sectors",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                help_text="Sectors that the user is interested in",
                size=None,
            ),
        ),
    ]
