# Generated by Django 4.2.11 on 2024-10-23 11:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0038_alter_profile_organisations_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="countries",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                help_text="Countries that the user is interested in",
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="overseas_region",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                help_text="Overseas regions that the user is interested in",
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="trading_blocs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                help_text="Trading blocs that the user is interested in",
                size=None,
            ),
        ),
    ]
