# Generated by Django 4.2.11 on 2024-10-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0039_profile_countries_profile_overseas_region_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="overseas_region",
            new_name="overseas_regions",
        ),
    ]
