# Generated by Django 4.2.11 on 2024-10-24 10:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0049_initial_policy_teams"),
        ("user", "0040_rename_overseas_region_profile_overseas_regions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="organisations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Organisations that the user is interested in",
                to="metadata.organisation",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="policy_teams",
            field=models.ManyToManyField(
                blank=True,
                help_text="Policy teams that the user is interested in",
                to="metadata.policyteam",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="trading_blocs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("TB00003", "Association of Southeast Asian Nations (ASEAN)"),
                        ("TB00016", "European Union (EU)"),
                        ("TB00017", "Gulf Cooperation Council (GCC)"),
                        ("TB00013", "Eurasian Economic Union (EAEU)"),
                        ("TB00026", "Southern Common Market (Mercosur)"),
                    ],
                    max_length=7,
                ),
                blank=True,
                default=list,
                help_text="Trading blocs that the user is interested in",
                size=None,
            ),
        ),
    ]
