# Generated by Django 4.2.11 on 2024-11-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0049_initial_policy_teams"),
        ("user", "0042_alter_profile_policy_teams"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="policy_teams",
            field=models.ManyToManyField(
                blank=True,
                help_text="Policy teams that the user is interested in",
                null=True,
                to="metadata.policyteam",
            ),
        ),
    ]
