# Generated by Django 3.1.2 on 2020-10-27 09:45
from django.db import migrations


def add_permissions(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    PreliminaryAssessment = apps.get_model("assessment", "PreliminaryAssessment")
    analyst_group = Group.objects.get(name="Analyst")
    content_type = ContentType.objects.get_for_model(PreliminaryAssessment)
    permission_add, _ = Permission.objects.get_or_create(codename="add_preliminaryassessment", defaults={"name": "Can add preliminary assessment", "content_type_id": content_type.id})
    permission_change, _ = Permission.objects.get_or_create(codename="change_preliminaryassessment", defaults={"name": "Can change preliminary assessment", "content_type_id": content_type.id})

    analyst_group.permissions.add(
        permission_add,
        permission_change,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0043_alter_profile_policy_teams"),
        ("assessment", "0024_preliminaryassessment_and_more"),
    ]

    operations = [
        migrations.RunPython(
            add_permissions, reverse_code=migrations.RunPython.noop
        ),
    ]
