# Generated by Django 3.1.2 on 2020-10-27 09:45
from django.db import migrations


def add_permissions(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")

    analyst_group = Group.objects.get(name="Analyst")
    content_type = ContentType.objects.get(app_label="assessment", model="preliminaryassessment")
    permission_add = Permission.objects.create(name="Can add preliminary assessment", content_type=content_type, codename="add_preliminaryassessment")
    permission_change = Permission.objects.create(name="Can change preliminary assessment", content_type=content_type, codename="change_preliminaryassessment")

    analyst_group.permissions.add(
        permission_add,
        permission_change,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0043_alter_profile_policy_teams"),
    ]

    operations = [
        migrations.RunPython(
            add_permissions, reverse_code=migrations.RunPython.noop
        ),
    ]
