# Generated by Django 2.0.5 on 2018-06-18 11:27

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_status', models.PositiveIntegerField(choices=[(1, "It hasn't happened yet"), (2, "It's happening now"), (3, 'It happened in the past')], null=True)),
                ('is_emergency', models.BooleanField(default=False)),
                ('company_id', models.UUIDField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_id', models.UUIDField(blank=True, null=True)),
                ('product', models.CharField(blank=True, max_length=255, null=True)),
                ('commodity_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=None, max_length=10, null=True), null=True, size=None)),
                ('export_country', models.CharField(blank=True, max_length=255, null=True)),
                ('problem_description', models.TextField(null=True)),
                ('problem_impact', models.TextField(null=True)),
                ('estimated_loss_range', models.PositiveIntegerField(choices=[(1, 'Less than £1m'), (2, '£1m to £10m'), (3, '£10m to £100m'), (4, 'Over £100m')], null=True)),
                ('other_companies_affected', models.PositiveIntegerField(choices=[(1, 'Yes'), (2, 'No'), (3, "Don't know")], null=True)),
                ('govt_response_requester', models.PositiveIntegerField(choices=[(1, 'None, this is for our information only at this stage'), (2, 'In-country support from post'), (3, 'Broader UK government sensitivities')], null=True)),
                ('is_confidential', models.NullBooleanField()),
                ('sensitivity_summary', models.TextField(null=True)),
                ('can_publish', models.PositiveIntegerField(choices=[(1, 'Yes'), (2, 'No'), (3, "Don't publish without consultation")], null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('summary', models.TextField(null=True)),
                ('status', models.PositiveIntegerField(choices=[(0, 'Unfinished'), (1, 'AwaitingScreening'), (2, 'Accepted'), (3, 'Rejected'), (4, 'Archived')], default=0)),
                ('status_comments', models.TextField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'NOT STARTED'), (2, 'IN PROGRESS'), (3, 'COMPLETED')], null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.Report')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='reportstage',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.Stage'),
        ),
        migrations.AddField(
            model_name='report',
            name='stages',
            field=models.ManyToManyField(related_name='report_stages', through='reports.ReportStage', to='reports.Stage'),
        ),
        migrations.AlterUniqueTogether(
            name='reportstage',
            unique_together={('report', 'stage')},
        ),
    ]
