# Generated by Django 2.0.5 on 2018-06-18 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20180618_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.Stage'),
        ),
    ]
