# Generated by Django 2.0.5 on 2018-07-04 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
        ('reports', '0007_report_company_sector'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='name',
            new_name='barrier_title',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='sensitivity_summary',
            new_name='commercial_sensitivity_summary',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='is_confidential',
            new_name='is_politically_sensitive',
        ),
        migrations.RemoveField(
            model_name='report',
            name='summary',
        ),
        migrations.AddField(
            model_name='report',
            name='barrier_type',
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.BarrierType'),
        ),
        migrations.AddField(
            model_name='report',
            name='fta_infingment',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='report',
            name='has_legal_infringment',
            field=models.PositiveIntegerField(
                choices=[(1, 'Yes'), (2, 'No'), (3, "Don't know")], null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='infringment_summary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='is_commercially_sensitive',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='report',
            name='other_companies_info',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='other_infingment',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='report',
            name='political_sensitivity_summary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='steps_taken',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='wto_infingment',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='commodity_codes',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='export_country',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='support_type',
            field=models.PositiveIntegerField(choices=[(
                1, 'Market access team to take over the lead'), (2, "None, I'm going to hendle next steps myself")], null=True),
        ),
        migrations.AlterField(
            model_name='reportstage',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='progress', to='reports.Stage'),
        ),
    ]
