# Generated by Django 2.0.5 on 2018-07-09 06:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0009_auto_20180704_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='is_emergency',
            field=models.NullBooleanField(),
        ),
    ]
