# Generated by Django 2.0.5 on 2018-07-09 10:15

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0010_auto_20180709_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='barrier_type',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.BarrierType'),
        ),
    ]
