# Generated by Django 2.0.5 on 2018-07-09 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0011_auto_20180709_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.PositiveIntegerField(choices=[(0, 'Unfinished'), (1, 'AwaitingScreening'), (2, 'Accepted'), (3, 'Rejected'), (4, 'Archived')], default=0)),
                ('comments', models.TextField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='status_comments',
        ),
        migrations.AlterField(
            model_name='report',
            name='barrier_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_barrier', to='metadata.BarrierType'),
        ),
        migrations.AlterField(
            model_name='report',
            name='support_type',
            field=models.PositiveIntegerField(choices=[(1, 'Market access team to provide support on next steps'), (2, 'None, I’m going to handle next steps myself as the lead coordinator')], null=True),
        ),
        migrations.AddField(
            model_name='reportstatus',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_status', to='reports.Report'),
        ),
    ]
