# Generated by Django 2.0.5 on 2018-07-12 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0014_auto_20180711_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name="report", 
            old_name="company_sector", 
            new_name="company_sector_id"
        ),
        migrations.AddField(
            model_name='report',
            name='company_sector_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
