# Generated by Django 2.0.5 on 2018-07-13 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reports", "0015_auto_20180712_1156")]

    operations = []
