# Generated by Django 2.0.5 on 2018-09-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("reports", "0016_remove_report_status_comments")]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="problem_status",
            field=models.PositiveIntegerField(
                choices=[(1, "On the border"), (2, "Long term strategic barrier")],
                null=True,
            ),
        )
    ]
