# Generated by Django 2.0.5 on 2018-09-03 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reports", "0017_auto_20180903_1352")]

    operations = []
