# Generated by Django 2.0.5 on 2018-09-05 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_remove_report_status_comments'),
    ]

    operations = [
    ]
