BARRIER_FIELD_TO_COLUMN_TITLE = {
    "id": "id",
    "code": "code",
    "title": "Title",
    "summary": "Summary",
    "link": "Link",
    "status": "Status",
    "is_top_priority": "Is Top 100 Priority",
    "is_resolved_top_priority": "Is Resolved Top Priority",
    "priority_level": "Priority",
    "overseas_region": "Overseas Region",
    "location": "Location",
    "sectors": "Sectors",
    "policy_teams": "Policy Teams",
    "product": "Product",
    "admin_areas": "Admin areas",
    "reported_by": "Reported by",
    "reported_on": "Reported date",
    "barrier_owner": "Barrier Owner",
    "estimated_resolution_date": "Estimated resolution date",
    "proposed_estimated_resolution_date": "Proposed estimated resolution date",
    "status_date": "Status effective from date",
    "resolved_date": "Resolved date",
    "status_summary": "Status summary",
    "modified_on": "Last updated",
    "tags": "Tags",
    "trade_direction": "Trade direction",
    "government_organisations": "Related Organisations",
    "commodity_codes": "HS commodity codes",
    "economic_assessment_rating": "Economic assessment rating",
    "value_to_economy": "Value to economy",
    "valuation_assessment_rating": "Valuation assessment rating",
    "valuation_assessment_midpoint": "Midpoint value",
    "valuation_assessment_explanation": "Valuation assessment explanation",
    "commercial_value": "Commercial value estimate",
    "public_view_status": "Public view status",
    "changed_since_published": "Changed since published",
    "public_title": "Public title",
    "public_summary": "Public summary",
    "progress_update_status": "Progress update status",
    "progress_update_message": "Progress update message",
    "progress_update_next_steps": "Progress update next steps",
    "next_steps_items": "Progress update list of next steps",
    "programme_fund_progress_update_milestones": "Programme fund milestones",
    "programme_fund_progress_update_expenditure": "Programme fund expenditure",
    "programme_fund_progress_update_date": "Programme fund date",
    "programme_fund_progress_update_author": "Programme fund author",
}
