repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        exclude: migrations
  - repo: http://github.com/PyCQA/isort
    rev: 5.11.5
    hooks:
      - id: isort
        exclude: migrations
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args: ["--config=.flake8"]
        exclude: migrations
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        files: core/frontend/src
        exclude: core/frontend/src/js/vendor
        types: [javascript]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.13.0
    hooks:
      - id: eslint
        files: core/frontend/src
        args: ["--fix"]
        additional_dependencies:
          - prettier@2.3.1
          - eslint@7.25.0
          - eslint-config-prettier@8.3.0
          - eslint-plugin-prettier@3.4.0
        types: [javascript]
        exclude: core/frontend/src/js/vendor
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.2.0
    hooks:
      - id: detect-secrets
        args: ["--exclude-files", "README.md"]
  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.17
    hooks:
      - id: circleci-config-validate
