version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file: docker-compose.env
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    env_file: docker-compose.env
    ports:
      - "8000:8000"
    depends_on:
      - db
  celery:
    build:
      context: .
    volumes:
      - .:/app
    entrypoint: dockerize -wait tcp://web:8000 -timeout 60s
    env_file: docker-compose.env
    depends_on:
      - web
    links:
      - web
    command: celery worker -A config.celery -l info -B
