country_mapping = {
    "Bolivia": "Bolivia (Plurinational State of)",
    "Bosnia and Herzegovina": "Bosnia Herzegovina",
    "British Virgin Islands": "Br. Virgin Isds",
    "Brunei": "Brunei Darussalam",
    "Cape Verde": "Cabo Verde",
    "Cayman Islands": "Cayman Isds",
    "Central African Republic": "Central African Rep.",
    "Congo (Democratic Republic)": "Dem. Rep. of the Congo",
    "Dominican Republic": "Dominican Rep.",
    "East Timor": "Timor-Leste",
    "Eswatini": "Swaziland",
    "Falkland Islands": "Falkland Isds (Malvinas)",
    "Faroe Islands": "Faeroe Isds",
    "Hong Kong": "China, Hong Kong SAR",
    "Ivory Coast": "Côte d'Ivoire",
    "Laos": "Lao People's Dem. Rep.",
    "Macao": "China, Macao SAR",
    "Marshall Islands": "Marshall Isds",
    "Micronesia": "FS Micronesia",
    "Moldova": "Rep. of Moldova",
    "Myanmar (Burma)": "Myanmar",
    "Netherlands Antilles": "Neth. Antilles",
    "North Korea": "Dem. People's Rep. of Korea",
    "Occupied Palestinian Territories": "State of Palestine",
    "Russia": "Russian Federation",
    "Solomon Islands": "Solomon Isds",
    "South Korea": "Rep. of Korea",
    "St Kitts and Nevis": "Saint Kitts and Nevis",
    "St Lucia": "Saint Lucia",
    "St Martin": "Saint Maarten",
    "St Vincent": "Saint Vincent and the Grenadines",
    "Tanzania": "United Rep. of Tanzania",
    "The Bahamas": "Bahamas",
    "The Gambia": "Gambia",
    "Turks and Caicos Islands": "Turks and Caicos Isds",
    "United States": "USA",
    "United States Virgin Islands": "US Virgin Isds",
    "Vatican City": "Holy See (Vatican City State)",
    "Vietnam": "Viet Nam",
}


def get_comtrade_country_name(country_name: str):
    return country_mapping.get(country_name, country_name)
