# Generated by Django 3.1.10 on 2021-06-07 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barriers', '0109_publicbarrierlighttouchreviews_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('barrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_plans', to='barriers.barrier')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_action_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActionPlanMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('objective', models.TextField()),
                ('completion_date', models.DateField()),
                ('action_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='action_plans.actionplan')),
            ],
        ),
        migrations.CreateModel(
            name='ActionPlanTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('action_text', models.TextField()),
                ('action_type', models.CharField(choices=[('SCOPING_AND_RESEARCH', 'Scoping/Research'), ('LOBBYING', 'Lobbying'), ('UNILATERAL_INTERVENTIONS', 'Unilateral interventions'), ('BILATERAL_ENGAGEMENT', 'Bilateral engagement'), ('PLURILATERAL_ENGAGEMENT', 'Plurilateral engagement'), ('MULTILATERAL_ENGAGEMENT', 'Multilateral engagement'), ('EVENT', 'Event'), ('WHITEHALL_FUNDING_STREAMS', 'Whitehall funding streams'), ('RESOLUTION_NOT_LEAD_BY_DIT', 'Resolution not lead by DIT')], max_length=100)),
                ('action_type_category', models.CharField(blank=True, max_length=100, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='action_plans.actionplanmilestone')),
            ],
        ),
    ]
