# Generated by Django 3.1.10 on 2021-06-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionplantask',
            name='stakeholders',
            field=models.TextField(blank=True, default=''),
        ),
    ]
