# Generated by Django 3.1.10 on 2021-06-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_plans', '0002_actionplantask_stakeholders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionplantask',
            name='action_type',
            field=models.CharField(choices=[('SCOPING_AND_RESEARCH', 'Scoping/Research'), ('LOBBYING', 'Lobbying'), ('UNILATERAL_INTERVENTIONS', 'Unilateral interventions'), ('BILATERAL_ENGAGEMENT', 'Bilateral engagement'), ('PLURILATERAL_ENGAGEMENT', 'Plurilateral engagement'), ('MULTILATERAL_ENGAGEMENT', 'Multilateral engagement'), ('EVENT', 'Event'), ('WHITEHALL_FUNDING_STREAMS', 'Whitehall funding streams'), ('RESOLUTION_NOT_LEAD_BY_DIT', 'Resolution not lead by DIT'), ('OTHER', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='actionplantask',
            name='action_type_category',
            field=models.CharField(blank=True, default='Other', max_length=100, null=True),
        ),
    ]
