# Generated by Django 3.1.10 on 2021-06-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_plans', '0003_auto_20210615_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionplan',
            name='current_status',
            field=models.TextField(blank=True, default=''),
        ),
    ]
