# Generated by Django 3.1.10 on 2021-06-16 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action_plans', '0004_actionplan_current_status'),
    ]

    operations = [
    ]
