# Generated by Django 3.1.10 on 2021-06-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_plans', '0005_add_owner_to_action_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionplan',
            name='current_status_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
