# Generated by Django 3.1.12 on 2021-07-06 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action_plans', '0006_actionplan_current_status_last_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionplantask',
            options={'ordering': ('start_date', 'completion_date')},
        ),
    ]
