# Generated by Django 3.1.12 on 2021-07-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_plans', '0007_auto_20210706_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionplan',
            name='status',
            field=models.CharField(blank=True, choices=[('ON_TRACK', 'On track'), ('RISK_OF_DELAY', 'Risk of delay'), ('DELAYED', 'Delayed')], max_length=100, null=True),
        ),
    ]
