# Generated by Django 3.1.12 on 2021-07-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_plans', '0008_actionplan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionplan',
            name='strategic_context',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='actionplantask',
            name='outcome',
            field=models.TextField(blank=True, default=''),
        ),
    ]
