# Generated by Django 3.1.12 on 2021-07-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_plans', '0010_auto_20210713_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionplantask',
            name='progress',
            field=models.TextField(blank=True, default=''),
        ),
    ]
