# Generated by Django 3.1.13 on 2021-08-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_plans', '0012_historicalactionplan_historicalactionplanmilestone_historicalactionplantask'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionplan',
            name='strategic_context_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalactionplan',
            name='strategic_context_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
