# Generated by Django 3.1.13 on 2021-08-20 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0109_publicbarrierlighttouchreviews_enabled'),
        ('action_plans', '0013_auto_20210820_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionplan',
            name='barrier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='action_plans', to='barriers.barrier'),
        ),
    ]
