# Generated by Django 3.2.5 on 2021-08-24 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0109_publicbarrierlighttouchreviews_enabled'),
        ('action_plans', '0014_auto_20210820_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionplan',
            name='barrier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='action_plan', to='barriers.barrier'),
        ),
    ]
