# Generated by Django 3.2.5 on 2021-08-26 16:53

from django.db import migrations


def populate_action_plan_models(apps, schema_editor):
    Barrier = apps.get_model("barriers", "Barrier")
    ActionPlan = apps.get_model("action_plans", "ActionPlan")

    for barrier in Barrier.objects.filter(action_plan__isnull=True):
        ActionPlan(barrier=barrier).save()


class Migration(migrations.Migration):

    dependencies = [
        ("action_plans", "0015_alter_actionplan_barrier"),
    ]

    operations = [migrations.RunPython(populate_action_plan_models)]
