# Generated by Django 3.2.13 on 2022-07-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_plans', '0016_populate_action_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionplan',
            name='potential_risks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actionplan',
            name='potential_unwanted_outcomes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actionplan',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='actionplan',
            name='risk_mitigation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalactionplan',
            name='potential_risks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalactionplan',
            name='potential_unwanted_outcomes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalactionplan',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalactionplan',
            name='risk_mitigation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
