# Generated by Django 3.2.13 on 2022-07-20 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action_plans', '0017_auto_20220720_0738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionplan',
            old_name='risk_mitigation',
            new_name='risk_mitigation_measures',
        ),
        migrations.RenameField(
            model_name='historicalactionplan',
            old_name='risk_mitigation',
            new_name='risk_mitigation_measures',
        ),
    ]
