# Generated by Django 3.2.13 on 2022-07-13 16:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("action_plans", "0017_stakeholder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actionplantask",
            name="stakeholders",
        ),
        migrations.RemoveField(
            model_name="historicalactionplantask",
            name="stakeholders",
        ),
        migrations.AddField(
            model_name="actionplantask",
            name="assigned_stakeholders",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(), blank=True, default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="historicalactionplantask",
            name="assigned_stakeholders",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(), blank=True, default=list, size=None
            ),
        ),
    ]
