# Generated by Django 3.2.13 on 2022-07-21 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action_plans', '0018_auto_20220713_1620'),
        ('action_plans', '0018_auto_20220720_0833'),
    ]

    operations = [
    ]
