# Generated by Django 3.2.13 on 2022-07-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("action_plans", "0019_merge_0018_auto_20220713_1620_0018_auto_20220720_0833"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalactionplantask",
            name="assigned_stakeholders",
        ),
        migrations.RemoveField(
            model_name="actionplantask",
            name="assigned_stakeholders",
        ),
        migrations.AddField(
            model_name="actionplantask",
            name="assigned_stakeholders",
            field=models.ManyToManyField(blank=True, to="action_plans.Stakeholder"),
        ),
    ]
