# Generated by Django 3.2.13 on 2022-07-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("action_plans", "0020_auto_20220726_1257"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionplantask",
            name="reason_for_completion_date_change",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="historicalactionplantask",
            name="reason_for_completion_date_change",
            field=models.TextField(blank=True, default=""),
        ),
    ]
