# Generated by Django 3.2.13 on 2022-08-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_plans', '0021_auto_20220728_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionplan',
            name='has_risks',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalactionplan',
            name='has_risks',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=100, null=True),
        ),
    ]
