# Generated by Django 3.2.20 on 2023-10-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_plans', '0022_auto_20220818_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalactionplan',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical action plan', 'verbose_name_plural': 'historical action plans'},
        ),
        migrations.AlterModelOptions(
            name='historicalactionplanmilestone',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical action plan milestone', 'verbose_name_plural': 'historical action plan milestones'},
        ),
        migrations.AlterModelOptions(
            name='historicalactionplantask',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical action plan task', 'verbose_name_plural': 'historical action plan tasks'},
        ),
        migrations.AlterField(
            model_name='historicalactionplan',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalactionplanmilestone',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalactionplantask',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
