# Generated by Django 2.2.10 on 2020-03-20 12:28

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_auto_20190809_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalassessment',
            name='documents_cache',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), blank=True, default=list, null=True, size=None),
        ),
    ]
