# Generated by Django 2.2.8 on 2019-12-12 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_auto_20190809_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='barrier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='barriers.BarrierInstance'),
        ),
    ]
