# Generated by Django 2.2.10 on 2020-03-26 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_auto_20200325_1601'),
        ('assessment', '0004_auto_20191212_1542'),
    ]

    operations = [
    ]
