# Generated by Django 3.1.2 on 2020-11-02 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0009_resolvability_and_strategic_assessments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalresolvabilityassessment',
            name='approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalresolvabilityassessment',
            name='effort_to_resolve',
            field=models.PositiveIntegerField(choices=[(0, '0: Not resolvable'), (1, '1: Highly resource intensive (significant resources needed)'), (2, '2: substantial resources required (extras or significant reprioritisation of exsiting resources needed)'), (3, '3: moderate resources required (low or moderate prioritisation or resources needed)'), (4, '4: low resource requirement (can be delivered within existing resources)')]),
        ),
        migrations.AlterField(
            model_name='historicalresolvabilityassessment',
            name='reviewed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalresolvabilityassessment',
            name='time_to_resolve',
            field=models.PositiveIntegerField(choices=[(0, '0: not resolvable'), (1, '1: longer than 5 years'), (2, '2: 3 to 5 years'), (3, '3: 1 to 3 years'), (4, '4: within a year')]),
        ),
        migrations.AlterField(
            model_name='historicalstrategicassessment',
            name='approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstrategicassessment',
            name='reviewed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstrategicassessment',
            name='scale',
            field=models.PositiveIntegerField(choices=[(1, '1: 3 or more government wide objectives, or poses medium/high risk to delivery of one of government wide objectives and/or potential for significant PR issues.'), (2, '2: 1 or 2 government wide objectives but does not pose much risk for PR or objective delivery'), (3, '3: neutral to government wide objectives'), (4, '4: supports 1 or 2  government wide objectives'), (5, '5: substantial contribution to 1 strategic objective or supporting 3 or more strategic objectives')]),
        ),
        migrations.AlterField(
            model_name='resolvabilityassessment',
            name='approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resolvabilityassessment',
            name='effort_to_resolve',
            field=models.PositiveIntegerField(choices=[(0, '0: Not resolvable'), (1, '1: Highly resource intensive (significant resources needed)'), (2, '2: substantial resources required (extras or significant reprioritisation of exsiting resources needed)'), (3, '3: moderate resources required (low or moderate prioritisation or resources needed)'), (4, '4: low resource requirement (can be delivered within existing resources)')]),
        ),
        migrations.AlterField(
            model_name='resolvabilityassessment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resolvabilityassessment',
            name='reviewed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resolvabilityassessment',
            name='time_to_resolve',
            field=models.PositiveIntegerField(choices=[(0, '0: not resolvable'), (1, '1: longer than 5 years'), (2, '2: 3 to 5 years'), (3, '3: 1 to 3 years'), (4, '4: within a year')]),
        ),
        migrations.AlterField(
            model_name='strategicassessment',
            name='approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategicassessment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='strategicassessment',
            name='reviewed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategicassessment',
            name='scale',
            field=models.PositiveIntegerField(choices=[(1, '1: 3 or more government wide objectives, or poses medium/high risk to delivery of one of government wide objectives and/or potential for significant PR issues.'), (2, '2: 1 or 2 government wide objectives but does not pose much risk for PR or objective delivery'), (3, '3: neutral to government wide objectives'), (4, '4: supports 1 or 2  government wide objectives'), (5, '5: substantial contribution to 1 strategic objective or supporting 3 or more strategic objectives')]),
        ),
    ]
