# Generated by Django 3.1.2 on 2020-11-05 17:05

from django.db import migrations


def convert_null_to_empty(apps, schema_editor):
    Assessment = apps.get_model("assessment", "Assessment")
    HistoricalAssessment = apps.get_model("assessment", "HistoricalAssessment")
    ResolvabilityAssessment = apps.get_model("assessment", "ResolvabilityAssessment")
    HistoricalResolvabilityAssessment = apps.get_model(
        "assessment", "HistoricalResolvabilityAssessment"
    )
    StrategicAssessment = apps.get_model("assessment", "StrategicAssessment")
    HistoricalStrategicAssessment = apps.get_model(
        "assessment", "HistoricalStrategicAssessment"
    )

    assesment_fields = (
        "archived_reason",
        "commercial_value_explanation",
        "explanation",
        "impact",
    )

    for field in assesment_fields:
        Assessment.objects.filter(**{f"{field}__isnull": True}).update(**{field: ""})
        HistoricalAssessment.objects.filter(**{f"{field}__isnull": True}).update(
            **{field: ""}
        )

    ResolvabilityAssessment.objects.filter(archived_reason__isnull=True).update(
        archived_reason=""
    )
    HistoricalResolvabilityAssessment.objects.filter(
        archived_reason__isnull=True
    ).update(archived_reason="")
    StrategicAssessment.objects.filter(archived_reason__isnull=True).update(
        archived_reason=""
    )
    HistoricalStrategicAssessment.objects.filter(archived_reason__isnull=True).update(
        archived_reason=""
    )


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0010_auto_20201102_0943"),
    ]

    operations = [
        migrations.RunPython(
            convert_null_to_empty, reverse_code=migrations.RunPython.noop
        ),
    ]
