# Generated by Django 3.1.2 on 2020-11-20 11:09

from django.db import migrations


def migrate_old_assessments(apps, schema_editor):
    Barrier = apps.get_model("barriers", "Barrier")
    EconomicAssessment = apps.get_model("assessment", "EconomicAssessment")

    # Loop through and call .save() to ensure history gets triggered
    for barrier in Barrier.objects.filter(
        economic_assessments__isnull=False
    ).distinct():
        barrier.economic_assessment_eligibility = True
        barrier.save()

    for economic_assessment in EconomicAssessment.objects.filter(
        ready_for_approval=False
    ):
        economic_assessment.approved = True
        economic_assessment.ready_for_approval = True
        economic_assessment.reviewed_by = economic_assessment.created_by
        economic_assessment.reviewed_on = economic_assessment.created_on
        economic_assessment.save()


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0014_auto_20201119_1134"),
    ]

    operations = [
        migrations.RunPython(
            migrate_old_assessments, reverse_code=migrations.RunPython.noop
        ),
    ]
