# Generated by Django 3.1.2 on 2020-11-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0014_auto_20201116_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economicimpactassessment',
            name='impact',
            field=models.PositiveIntegerField(choices=[(1, '1: £ less than a thousand'), (2, '2: £ tens of thousands'), (3, '3: £ hundreds of thousands'), (4, '4: £ millions'), (5, '5: £ tens of millions'), (6, '6: £ hundreds of millions'), (7, '7: £ billions'), (8, '8: £ tens of billions')]),
        ),
        migrations.AlterField(
            model_name='historicaleconomicimpactassessment',
            name='impact',
            field=models.PositiveIntegerField(choices=[(1, '1: £ less than a thousand'), (2, '2: £ tens of thousands'), (3, '3: £ hundreds of thousands'), (4, '4: £ millions'), (5, '5: £ tens of millions'), (6, '6: £ hundreds of millions'), (7, '7: £ billions'), (8, '8: £ tens of billions')]),
        ),
    ]
