# Generated by Django 3.1.2 on 2020-11-20 11:09

from django.db import migrations
from django.db.models import F


def migrate_old_assessments(apps, schema_editor):
    Barrier = apps.get_model("barriers", "Barrier")
    EconomicAssessment = apps.get_model("assessment", "EconomicAssessment")

    Barrier.objects.filter(economic_assessments__isnull=False).update(economic_assessment_eligibility=True)
    EconomicAssessment.objects.filter(
        ready_for_approval=False,
    ).update(
        approved=True,
        ready_for_approval=True,
        reviewed_by=F("created_by"),
        reviewed_on=F("created_on"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0014_auto_20201119_1134'),
    ]

    operations = [
        migrations.RunPython(
            migrate_old_assessments,
            reverse_code=migrations.RunPython.noop
        ),
    ]

