# Generated by Django 3.2.7 on 2022-04-01 08:12

import django.db.models.deletion
from django.db import migrations, models


# For each valuation assessment add the barrier_id belonging to its parent economic assessment
def add_barrier_id_to_economic_impact_assessment(apps, schema_editor):
    EconomicImpactAssessment = apps.get_model("assessment", "EconomicImpactAssessment")
    for assessment in EconomicImpactAssessment.objects.all():
        assessment.barrier_id = assessment.economic_assessment.barrier_id
        assessment.save()


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0121_auto_20220325_1343"),
        ("assessment", "0020_migrate_old_to_new_impact_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="economicimpactassessment",
            name="barrier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="valuation_assessments",
                to="barriers.barrier",
            ),
        ),
        migrations.AddField(
            model_name="historicaleconomicimpactassessment",
            name="barrier",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="barriers.barrier",
            ),
        ),
        migrations.AlterField(
            model_name="economicimpactassessment",
            name="economic_assessment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="valuation_assessments",
                to="assessment.economicassessment",
            ),
        ),
        migrations.RunPython(
            add_barrier_id_to_economic_impact_assessment,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
