# Generated by Django 3.2.7 on 2022-04-01 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0021_auto_20220401_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economicimpactassessment',
            name='economic_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='economic_impact_assessments', to='assessment.economicassessment'),
        ),
    ]
