# Generated by Django 3.2.20 on 2023-11-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0022_alter_economicimpactassessment_economic_assessment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaleconomicassessment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical economic assessment', 'verbose_name_plural': 'historical economic assessments'},
        ),
        migrations.AlterModelOptions(
            name='historicaleconomicimpactassessment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical economic impact assessment', 'verbose_name_plural': 'historical economic impact assessments'},
        ),
        migrations.AlterModelOptions(
            name='historicalresolvabilityassessment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical resolvability assessment', 'verbose_name_plural': 'historical resolvability assessments'},
        ),
        migrations.AlterModelOptions(
            name='historicalstrategicassessment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical strategic assessment', 'verbose_name_plural': 'historical strategic assessments'},
        ),
        migrations.AlterField(
            model_name='historicaleconomicassessment',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaleconomicimpactassessment',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalresolvabilityassessment',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalstrategicassessment',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
