# Generated by Django 3.1.1 on 2020-09-01 15:11

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_event_log", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userevent",
            name="data",
            field=models.JSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder, null=True
            ),
        ),
    ]
