# Generated by Django 3.1.2 on 2020-11-05 17:15

from django.db import migrations


def convert_null_to_empty(apps, schema_editor):
    TeamMember = apps.get_model("collaboration", "TeamMember")
    HistoricalTeamMember = apps.get_model("collaboration", "HistoricalTeamMember")

    fields =(
        "archived_reason",
        "role",
    )

    for field in fields:
        TeamMember.objects.filter(**{f"{field}__isnull": True}).update(**{field: ""})
        HistoricalTeamMember.objects.filter(**{f"{field}__isnull": True}).update(**{field: ""})


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0005_team_members_overhaul'),
    ]

    operations = [
        migrations.RunPython(
            convert_null_to_empty,
            reverse_code=migrations.RunPython.noop
        ),
    ]
