# Generated by Django 3.2.20 on 2023-11-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0007_fix_blank_and_null'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalteammember',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical team member', 'verbose_name_plural': 'historical team members'},
        ),
        migrations.AlterField(
            model_name='historicalteammember',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
