# Generated by Django 2.0.5 on 2018-05-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barrier',
            old_name='company',
            new_name='company_id',
        ),
        migrations.RemoveField(
            model_name='barrier',
            name='contact',
        ),
        migrations.AddField(
            model_name='barrier',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barrier',
            name='export_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
