# Generated by Django 2.0.5 on 2018-05-30 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barriers', '0002_auto_20180523_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarrierCommodityCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BarrierReportStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'NOT_STARTED'), (2, 'IN_PROGRESS'), (3, 'COMPLETED')], null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommodityCode',
            fields=[
                ('code', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ReportStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('description', models.CharField(max_length=255)),
                ('status', models.PositiveIntegerField(choices=[(1, 'NOT_STARTED'), (2, 'IN_PROGRESS'), (3, 'COMPLETED')], null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='barrier',
            old_name='status',
            new_name='problem_status',
        ),
        migrations.RemoveField(
            model_name='barrier',
            name='description',
        ),
        migrations.RemoveField(
            model_name='barrier',
            name='title',
        ),
        migrations.AddField(
            model_name='barrier',
            name='barrier_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barrier',
            name='barrier_summary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='barrier',
            name='can_publish',
            field=models.PositiveIntegerField(choices=[(1, 'None'), (2, 'IN_COUNTRY_SUPPORT'), (3, 'GOVT_SENSITIVE')], null=True),
        ),
        migrations.AddField(
            model_name='barrier',
            name='contact_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='barrier',
            name='estimated_loss_range',
            field=models.PositiveIntegerField(choices=[(1, 'LESS_THAN_1M'), (2, '1M_TO_10M'), (3, '10M_TO_100M'), (3, 'OVER_100M')], null=True),
        ),
        migrations.AddField(
            model_name='barrier',
            name='govt_response_requester',
            field=models.PositiveIntegerField(choices=[(1, 'None'), (2, 'IN_COUNTRY_SUPPORT'), (3, 'GOVT_SENSITIVE')], null=True),
        ),
        migrations.AddField(
            model_name='barrier',
            name='is_confidential',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='barrier',
            name='other_companies_affected',
            field=models.PositiveIntegerField(choices=[(1, 'YES'), (2, 'NO'), (3, 'DONT KNOW')], null=True),
        ),
        migrations.AddField(
            model_name='barrier',
            name='problem_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='barrier',
            name='problem_impact',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='barrier',
            name='product',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barrier',
            name='sensitivity_summary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='barrierreportstage',
            name='barrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='barriers.Barrier'),
        ),
        migrations.AddField(
            model_name='barrierreportstage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='barrierreportstage',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='barriers.ReportStage'),
        ),
        migrations.AddField(
            model_name='barriercommoditycode',
            name='barrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='barriers.Barrier'),
        ),
        migrations.AddField(
            model_name='barriercommoditycode',
            name='commodity_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='barriers.CommodityCode'),
        ),
        migrations.AddField(
            model_name='barrier',
            name='commodity_codes',
            field=models.ManyToManyField(related_name='commodity_codes', through='barriers.BarrierCommodityCode', to='barriers.CommodityCode'),
        ),
        migrations.AddField(
            model_name='barrier',
            name='report_stages',
            field=models.ManyToManyField(related_name='report_stages', through='barriers.BarrierReportStage', to='barriers.ReportStage'),
        ),
        migrations.AlterUniqueTogether(
            name='barriercommoditycode',
            unique_together={('barrier', 'commodity_code')},
        ),
    ]
