# Generated by Django 2.0.5 on 2018-07-19 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0002_auto_20180717_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barrierinteraction',
            old_name='pin_it',
            new_name='pinned',
        ),
        migrations.RenameField(
            model_name='barrierinteraction',
            old_name='notes',
            new_name='text',
        ),
    ]
