# Generated by Django 2.0.5 on 2018-07-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("barriers", "0003_auto_20180719_1130")]

    operations = [
        migrations.AlterUniqueTogether(name="barrierstatus", unique_together=set()),
        migrations.AddField(
            model_name="barrierstatus",
            name="summary",
            field=models.TextField(
                help_text="status summary if provided by user", null=True
            ),
        ),
        migrations.AlterField(
            model_name="barriercontributor",
            name="kind",
            field=models.CharField(
                choices=[
                    ("INITIATOR", "Initiator"),
                    ("CONTRIBUTOR", "Contributor"),
                    ("LEAD", "Lead"),
                ],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="barrierinstance",
            name="chance_of_success",
            field=models.CharField(
                choices=[
                    ("HIGHLY_LIKELY", "Highly likely"),
                    ("LIKELY", "Likely"),
                    ("UNLIKELY", "Unlikely"),
                    ("HIGHLY_UNLIKELY", "Highly unlikely"),
                ],
                help_text="chance of success",
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="barrierinteraction",
            name="kind",
            field=models.CharField(choices=[("COMMENT", "Comment")], max_length=25),
        ),
        migrations.AddField(
            model_name="barrierstatus",
            name="status_date",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="date when status action occurred",
                null=True,
            ),
        ),
    ]
