# Generated by Django 2.0.5 on 2018-06-06 12:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('barriers', '0004_auto_20180531_2008'), ('barriers', '0005_auto_20180606_1005')]

    dependencies = [
        ('barriers', '0003_auto_20180530_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrier',
            name='can_publish',
            field=models.PositiveIntegerField(choices=[(1, 'YES'), (2, 'NO'), (3, 'DONT_PUBLISH_WITHOUT_CONSULTATION')], null=True),
        ),
        migrations.AddField(
            model_name='barriercommoditycode',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='barrier',
            name='commodity_codes',
        ),
        migrations.AddField(
            model_name='barrier',
            name='commodity_codes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=None, max_length=10, null=True), default=[], size=None),
            preserve_default=False,
        ),
    ]
