# Generated by Django 2.0.5 on 2018-05-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0003_auto_20180530_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrier',
            name='can_publish',
            field=models.PositiveIntegerField(choices=[(1, 'YES'), (2, 'NO'), (3, 'DONT_PUBLISH_WITHOUT_CONSULTATION')], null=True),
        ),
    ]
