# Generated by Django 2.0.5 on 2018-06-06 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0004_auto_20180531_2008_squashed_0005_auto_20180606_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportstage',
            name='parent',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='barriers.ReportStage'),
        ),
        migrations.AlterField(
            model_name='reportstage',
            name='code',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
