# Generated by Django 2.0.5 on 2018-06-06 12:46

from django.db import migrations


report_stage_items = [
    {
        'code': '1.0',
        'description': 'Report a problem',
        'sub_items': [
            {
                'code': '1.1',
                'description': 'Status of the problem'
            },
            {
                'code': '1.2',
                'description': 'Export company affected'
            },
            {
                'code': '1.3',
                'description': 'About the reporter'
            },
            {
                'code': '1.4',
                'description': 'About the problem'
            },
            {
                'code': '1.5',
                'description': 'Next steps the company affected have requested'
            },
        ]
    },
    {
        'code': '2.0',
        'description': 'Create a barrier record',
        'sub_items': []
    },
    {
        'code': '3.0',
        'description': 'Tell us what happens next',
        'sub_items': []
    },
]


def add_report_stages(apps, schema_editor):
    ReportStage = apps.get_model('barriers', 'ReportStage')
    for item in report_stage_items:
        stage = ReportStage(code=item['code'], description=item['description']).save()
        for sub_item in item['sub_items']:
            ReportStage(code=sub_item['code'],
                        description=sub_item['description'], parent=stage).save()


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0005_auto_20180606_1246'),
    ]

    operations = [
        migrations.RunPython(add_report_stages),
    ]
