# Generated by Django 2.0.5 on 2018-09-03 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

REPORT_STAGE_ITEMS = [
    {"code": "1.1", "description": "Nature of the problem"},
    {"code": "1.2", "description": "Status of the problem"},
    {"code": "1.3", "description": "Export Country"},
    {"code": "1.4", "description": "Sectors affected"},
    {"code": "1.5", "description": "About the problem"},
    {"code": "1.6", "description": "Barrier type"},
]

def add_report_stages(apps, schema_editor):
    Stage = apps.get_model("barriers", "Stage")
    for item in REPORT_STAGE_ITEMS:
        Stage(code=item["code"], description=item["description"]).save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barriers', '0005_auto_20180806_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarrierReportStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'NOT STARTED'), (2, 'IN PROGRESS'), (3, 'COMPLETED')], null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('description', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='barriers.Stage')),
            ],
        ),
        migrations.RemoveField(
            model_name='barrierinstance',
            name='report',
        ),
        migrations.AddField(
            model_name='barrierinstance',
            name='barrier_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barrierinstance',
            name='commodity_codes',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barrierinstance',
            name='export_country',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='barrierinstance',
            name='is_resolved',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='barrierinstance',
            name='other_source',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barrierinstance',
            name='problem_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='barrierinstance',
            name='problem_impact',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='barrierinstance',
            name='problem_status',
            field=models.PositiveIntegerField(choices=[(1, 'On the border'), (2, 'Long term strategic barrier')], null=True),
        ),
        migrations.AddField(
            model_name='barrierinstance',
            name='product',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barrierinstance',
            name='resolved_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='barrierinstance',
            name='sectors_affected',
            field=models.NullBooleanField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barrierinstance',
            name='sectors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=None, null=True, size=None),
        ),
        migrations.AddField(
            model_name='barrierinstance',
            name='source',
            field=models.CharField(choices=[('COMPANY', 'Company'), ('TRADE', 'Trade Association'), ('GOVT', 'Government Lead'), ('OTHER', 'Other')], help_text='chance of success', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='barrierinstance',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Unfinished'), (1, 'Screening'), (2, 'Open'), (3, 'Rejected'), (4, 'Resolved'), (5, 'Hibernated'), (6, 'Archived')], default=0, help_text='status of the barrier instance'),
        ),
        migrations.AddField(
            model_name='barrierinstance',
            name='status_date',
            field=models.DateTimeField(auto_now_add=True, help_text='date when status action occurred', null=True),
        ),
        migrations.AddField(
            model_name='barrierinstance',
            name='status_summary',
            field=models.TextField(help_text='status summary if provided by user', null=True),
        ),
        migrations.AlterField(
            model_name='barrierinstance',
            name='barrier_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barrier_type', to='metadata.BarrierType'),
        ),
        migrations.AlterField(
            model_name='barrierstatus',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Unfinished'), (1, 'Screening'), (2, 'Open'), (3, 'Rejected'), (4, 'Resolved'), (5, 'Hibernated'), (6, 'Archived')], help_text='status of the barrier instance'),
        ),
        migrations.AddField(
            model_name='barrierreportstage',
            name='barrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress', to='barriers.BarrierInstance'),
        ),
        migrations.AddField(
            model_name='barrierreportstage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='barrierreportstage',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='barriers.Stage'),
        ),
        migrations.AddField(
            model_name='barrierinstance',
            name='stages',
            field=models.ManyToManyField(help_text='Store reporting stages before submitting', related_name='report_stages', through='barriers.BarrierReportStage', to='barriers.Stage'),
        ),
        migrations.AlterUniqueTogether(
            name='barrierreportstage',
            unique_together={('barrier', 'stage')},
        ),
        migrations.AlterField(
            model_name='barrierinstance',
            name='estimated_loss_range',
            field=models.PositiveIntegerField(choices=[(1, 'Less than £1m'), (2, '£1m to £10m'), (3, '£10m to £100m'), (4, 'Over £100m')], default=None, help_text='Estimated financial value of sales lost over a five year period', null=True),
        ),
        migrations.AlterField(
            model_name='barrierinstance',
            name='has_legal_infringement',
            field=models.PositiveIntegerField(choices=[(1, 'Yes'), (2, 'No'), (3, "Don't know")], default=None, help_text='Legal obligations infringed', null=True),
        ),
        migrations.AlterField(
            model_name='barrierinstance',
            name='infringement_summary',
            field=models.TextField(default=None, help_text='Summary of infringments', null=True),
        ),
        migrations.AlterField(
            model_name='barrierinstance',
            name='other_companies_affected',
            field=models.PositiveIntegerField(choices=[(1, 'Yes'), (2, 'No'), (3, "Don't know")], default=None, help_text='Are there other companies affected?', null=True),
        ),
        migrations.AlterField(
            model_name='barrierinstance',
            name='status_summary',
            field=models.TextField(default=None, help_text='status summary if provided by user', null=True),
        ),
        migrations.AlterField(
            model_name='barrierinstance',
            name='sectors_affected',
            field=models.NullBooleanField(),
        ),
        migrations.RunPython(add_report_stages),
    ]
