# Generated by Django 2.0.5 on 2018-06-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0006_auto_20180606_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportstage',
            name='parent',
        ),
        migrations.AlterField(
            model_name='barrier',
            name='can_publish',
            field=models.PositiveIntegerField(choices=[(1, 'Yes'), (2, 'No'), (3, "Don't publish without consultation")], null=True),
        ),
        migrations.AlterField(
            model_name='barrier',
            name='estimated_loss_range',
            field=models.PositiveIntegerField(choices=[(1, 'Less than £1m'), (2, '£1m to £10m'), (3, '£10m to £100m'), (4, 'Over £100m')], null=True),
        ),
        migrations.AlterField(
            model_name='barrier',
            name='govt_response_requester',
            field=models.PositiveIntegerField(choices=[(1, 'None, this is for our information only at this stage'), (2, 'In-country support from post'), (3, 'Broader UK government sensitivities')], null=True),
        ),
        migrations.AlterField(
            model_name='barrier',
            name='other_companies_affected',
            field=models.PositiveIntegerField(choices=[(1, 'Yes'), (2, 'No'), (3, "Don't know")], null=True),
        ),
        migrations.AlterField(
            model_name='barrier',
            name='problem_status',
            field=models.PositiveIntegerField(choices=[(1, "It hasn't happened yet"), (2, "It's happening now"), (3, 'It happened in the past')], null=True),
        ),
        migrations.AlterField(
            model_name='barrierreportstage',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'NOT STARTED'), (2, 'IN PROGRESS'), (3, 'COMPLETED')], null=True),
        ),
        migrations.AlterField(
            model_name='reportstage',
            name='code',
            field=models.CharField(max_length=4),
        ),
    ]
