# Generated by Django 2.0.5 on 2018-06-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0008_auto_20180607_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrier',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Unfinished'), (1, 'Screening'), (2, 'Assesment'), (3, 'Rejected'), (4, 'Resolved'), (5, 'Hibernated'), (6, 'Archived')], default=0),
        ),
    ]
