# Generated by Django 2.0.5 on 2018-06-11 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0009_barrier_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='barrierreportstage',
            unique_together={('barrier', 'stage', 'status')},
        ),
    ]
