# Generated by Django 2.0.5 on 2018-06-17 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0010_auto_20180611_1419'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='barrierreportstage',
            unique_together={('barrier', 'stage')},
        ),
    ]
