# Generated by Django 2.0.5 on 2018-06-18 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0011_auto_20180617_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barrier',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='barrier',
            name='report_stages',
        ),
        migrations.AlterUniqueTogether(
            name='barriercommoditycode',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='barriercommoditycode',
            name='barrier',
        ),
        migrations.RemoveField(
            model_name='barriercommoditycode',
            name='commodity_code',
        ),
        migrations.AlterUniqueTogether(
            name='barrierreportstage',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='barrierreportstage',
            name='barrier',
        ),
        migrations.RemoveField(
            model_name='barrierreportstage',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='barrierreportstage',
            name='stage',
        ),
        migrations.DeleteModel(
            name='Barrier',
        ),
        migrations.DeleteModel(
            name='BarrierCommodityCode',
        ),
        migrations.DeleteModel(
            name='BarrierReportStage',
        ),
        migrations.DeleteModel(
            name='ReportStage',
        ),
    ]
