# Generated by Django 2.0.5 on 2018-10-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0016_auto_20181003_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrierinstance',
            name='barrier_type_category',
            field=models.CharField(choices=[('GOODS', 'Goods'), ('SERVICES', 'Services')], default=None, help_text='barrier type category', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='historicalbarrierinstance',
            name='barrier_type_category',
            field=models.CharField(choices=[('GOODS', 'Goods'), ('SERVICES', 'Services')], default=None, help_text='barrier type category', max_length=25, null=True),
        ),
    ]
