# Generated by Django 2.1.2 on 2018-10-23 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0018_auto_20181022_2148"),
        ("barriers", "0018_auto_20181012_1426"),
    ]

    operations = []
