# Generated by Django 2.1.2 on 2018-12-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0020_auto_20181025_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrierinstance',
            name='priority',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='UNKNOWN', help_text='priority of the barrier instance', max_length=25),
        ),
        migrations.AddField(
            model_name='barrierinstance',
            name='priority_date',
            field=models.DateTimeField(auto_now=True, help_text='date when priority was set', null=True),
        ),
        migrations.AddField(
            model_name='barrierinstance',
            name='priority_summary',
            field=models.TextField(default=None, help_text='priority summary if provided by user', null=True),
        ),
        migrations.AddField(
            model_name='historicalbarrierinstance',
            name='priority',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='UNKNOWN', help_text='priority of the barrier instance', max_length=25),
        ),
        migrations.AddField(
            model_name='historicalbarrierinstance',
            name='priority_date',
            field=models.DateTimeField(blank=True, editable=False, help_text='date when priority was set', null=True),
        ),
        migrations.AddField(
            model_name='historicalbarrierinstance',
            name='priority_summary',
            field=models.TextField(default=None, help_text='priority summary if provided by user', null=True),
        ),
    ]
