# Generated by Django 2.1.5 on 2019-01-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0023_auto_20190116_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrierinstance',
            name='next_steps_summary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historicalbarrierinstance',
            name='next_steps_summary',
            field=models.TextField(null=True),
        ),
    ]
