# Generated by Django 2.1.5 on 2019-03-06 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0027_auto_20190228_1723'),
        ('barriers', '0027_auto_20190226_1442'),
    ]

    operations = [
    ]
