# Generated by Django 2.1.5 on 2019-04-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0029_barrierinstance_barrier_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrierinstance',
            name='status_date',
            field=models.DateField(help_text='date when status action occurred', null=True),
        ),
        migrations.AlterField(
            model_name='historicalbarrierinstance',
            name='status_date',
            field=models.DateField(help_text='date when status action occurred', null=True),
        ),
    ]
