# Generated by Django 2.1.5 on 2019-04-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0029_barrierinstance_barrier_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrierinstance',
            name='all_sectors',
            field=models.NullBooleanField(help_text='boolean to signify that all sectors are affected by this barrier'),
        ),
        migrations.AddField(
            model_name='historicalbarrierinstance',
            name='all_sectors',
            field=models.NullBooleanField(help_text='boolean to signify that all sectors are affected by this barrier'),
        ),
        migrations.AlterField(
            model_name='barrierinstance',
            name='sectors_affected',
            field=models.NullBooleanField(help_text='boolean to signify one or more sectors are affected by this barrier'),
        ),
        migrations.AlterField(
            model_name='historicalbarrierinstance',
            name='sectors_affected',
            field=models.NullBooleanField(help_text='boolean to signify one or more sectors are affected by this barrier'),
        ),
    ]
