# Generated by Django 2.2 on 2019-05-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0030_auto_20190415_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrierinstance',
            name='resolved_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbarrierinstance',
            name='resolved_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
