# Generated by Django 2.2.2 on 2019-07-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0031_auto_20190712_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrierinstance',
            name='resolved_status',
            field=models.CharField(choices=[('IN_FULL', 'In Full'), ('IN_PART', 'In Part')], help_text='chance of success', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='historicalbarrierinstance',
            name='resolved_status',
            field=models.CharField(choices=[('IN_FULL', 'In Full'), ('IN_PART', 'In Part')], help_text='chance of success', max_length=25, null=True),
        ),
    ]
