# Generated by Django 2.2.4 on 2019-08-29 13:42

from django.db import migrations

report_stage_items = [
    {
        "code": "1.0",
        "sub_items": [
            {"code": "1.1", "description": "Barrier status"},
            {"code": "1.5", "description": "Barrier summary"},
        ],
    }
]


def edit_report_stages(apps, schema_editor):
    Stage = apps.get_model("barriers", "Stage")
    for item in report_stage_items:
        parent_stage = Stage.objects.get(code=item["code"])
        for sub_item in item["sub_items"]:
            try:
                sub_stage = Stage.objects.get(code=sub_item["code"])
                sub_stage.description = sub_item["description"]
                sub_stage.save()
            except Stage.DoesNotExist:
                Stage(
                    code=sub_item["code"],
                    description=sub_item["description"],
                    parent=parent_stage,
                ).save()


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0032_auto_20190722_0905"),
    ]

    operations = [migrations.RunPython(edit_report_stages)]
