# Generated by Django 2.2.4 on 2019-10-23 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0034_auto_20191017_1434"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="barrierinstance",
            name="barrier_type_category",
        ),
        migrations.RemoveField(
            model_name="historicalbarrierinstance",
            name="barrier_type_category",
        ),
    ]
