# Generated by Django 2.2.8 on 2019-12-12 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0035_auto_20191023_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrierreportstage',
            name='barrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='barriers.BarrierInstance'),
        ),
    ]
