# Generated by Django 2.2.8 on 2020-02-24 16:22

from django.db import migrations


def populate_archived_reason(apps, schema_editor):
    BarrierInstance = apps.get_model("barriers", "BarrierInstance")
    BarrierInstance.objects.filter(
        archived=True,
        archived_reason__isnull=True,
    ).update(archived_reason="OTHER", archived_explanation="Archive reason unknown")


def unpopulate_archived_reason(apps, schema_editor):
    BarrierInstance = apps.get_model("barriers", "BarrierInstance")
    BarrierInstance.objects.filter(
        archived=True,
        archived_reason="OTHER",
        archived_explanation="Archive reason unknown",
    ).update(
        archived_reason=None,
        archived_explanation=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0037_auto_20200224_1552"),
    ]

    operations = [
        migrations.RunPython(populate_archived_reason, unpopulate_archived_reason),
    ]
