# Generated by Django 2.2.10 on 2020-03-18 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0039_auto_20200228_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrierinstance',
            name='barrier_types',
            field=models.ManyToManyField(help_text='Barrier categories', related_name='barriers', to='metadata.BarrierType'),
        ),
    ]
