# Generated by Django 2.2.10 on 2020-03-23 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0039_auto_20200228_1046"),
        ("barriers", "0036_auto_20191212_1542"),
    ]

    operations = []
