# Generated by Django 2.2.10 on 2020-03-25 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0041_barrieruserhit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrierinstance',
            name='barrier_types',
            field=models.ManyToManyField(help_text='Barrier categories', related_name='barriers', to='metadata.BarrierType'),
        ),
    ]
