# Generated by Django 2.2.10 on 2020-03-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0042_auto_20200325_1036"),
    ]

    operations = [
        migrations.RenameField(
            model_name="barrierinstance",
            old_name="barrier_types",
            new_name="categories",
        ),
    ]
