# Generated by Django 2.2.10 on 2020-03-26 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0043_auto_20200325_1458'),
        ('barriers', '0041_barrieruserhit'),
    ]

    operations = [
    ]
