# Generated by Django 2.2.11 on 2020-03-31 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0013_barriertag'),
        ('barriers', '0046_auto_20200327_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrierinstance',
            name='tags',
            field=models.ManyToManyField(to='metadata.BarrierTag'),
        ),
        # TODO: did Dan forget about this?
        #       also, consider to CASCADE instead of DO_NOTHING
        # migrations.AlterField(
        #     model_name='historicalbarrierinstance',
        #     name='priority',
        #     field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='metadata.BarrierPriority'),
        # ),
    ]
