# Generated by Django 2.2.11 on 2020-03-31 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0013_barriertag'),
        ('barriers', '0046_auto_20200327_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrierinstance',
            name='tags',
            field=models.ManyToManyField(to='metadata.BarrierTag'),
        ),
    ]
