# Generated by Django 2.2.10 on 2020-04-07 07:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0052_auto_20200331_0643"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalbarrierinstance",
            name="tags_cache",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), default=list, null=True, size=None
            ),
        ),
    ]
