# Generated by Django 2.2.11 on 2020-04-08 15:10

from django.db import migrations


def populate_covid_tags(apps, schema_editor):
    BarrierInstance = apps.get_model("barriers", "BarrierInstance")
    HistoricalBarrierInstance = apps.get_model("barriers", "HistoricalBarrierInstance")
    BarrierTag = apps.get_model("metadata", "BarrierTag")

    covid_tag = BarrierTag.objects.get(title="COVID-19")
    for barrier in BarrierInstance.objects.filter(barrier_title__icontains="COVID"):
        barrier.tags.add(covid_tag)

    HistoricalBarrierInstance.objects.filter(
        barrier_title__icontains="COVID"
    ).update(tags_cache=[covid_tag.id])


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0055_auto_20200403_2257'),
    ]

    operations = [
        migrations.RunPython(
            populate_covid_tags,
            reverse_code=migrations.RunPython.noop
        ),
    ]
