# Generated by Django 2.2.11 on 2020-04-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0058_auto_20200414_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrierinstance',
            name='is_summary_sensitive',
            field=models.NullBooleanField(help_text='Does the summary contain sensitive information'),
        ),
        migrations.AlterField(
            model_name='historicalbarrierinstance',
            name='is_summary_sensitive',
            field=models.NullBooleanField(help_text='Does the summary contain sensitive information'),
        ),
    ]
