# Generated by Django 2.2.11 on 2020-04-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0059_auto_20200415_1555"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barrierinstance",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="readable reference code",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
