# Generated by Django 2.2.11 on 2020-04-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0059_auto_20200415_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrierinstance',
            name='end_date',
            field=models.DateField(help_text='Date the barrier ends', null=True),
        ),
        migrations.AddField(
            model_name='barrierinstance',
            name='is_temporary',
            field=models.NullBooleanField(help_text='Is the barrier temporary?'),
        ),
        migrations.AddField(
            model_name='historicalbarrierinstance',
            name='end_date',
            field=models.DateField(help_text='Date the barrier ends', null=True),
        ),
        migrations.AddField(
            model_name='historicalbarrierinstance',
            name='is_temporary',
            field=models.NullBooleanField(help_text='Is the barrier temporary?'),
        ),
    ]
