# Generated by Django 2.2.13 on 2020-07-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0014_hscode'),
        ('barriers', '0063_auto_20200428_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrierinstance',
            name='hs_codes',
            field=models.ManyToManyField(to='metadata.HSCode'),
        ),
    ]
