# Generated by Django 2.2.13 on 2020-07-22 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0001_initial'),
        ('barriers', '0063_auto_20200428_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarrierCommodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('barrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barriers.BarrierInstance')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodities.Commodity')),
            ],
        ),
        migrations.AddField(
            model_name='barrierinstance',
            name='commodities',
            field=models.ManyToManyField(through='barriers.BarrierCommodity', to='commodities.Commodity'),
        ),
    ]
