# Generated by Django 2.2.12 on 2020-06-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0063_auto_20200428_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrierinstance',
            name='public_eligibility',
            field=models.BooleanField(default=None, help_text='Mark the barrier as either publishable or unpublishable to the public.', null=True),
        ),
        migrations.AddField(
            model_name='barrierinstance',
            name='public_eligibility_summary',
            field=models.TextField(default=None, help_text='Public eligibility summary if provided by user.', null=True),
        ),
        migrations.AddField(
            model_name='historicalbarrierinstance',
            name='public_eligibility',
            field=models.BooleanField(default=None, help_text='Mark the barrier as either publishable or unpublishable to the public.', null=True),
        ),
        migrations.AddField(
            model_name='historicalbarrierinstance',
            name='public_eligibility_summary',
            field=models.TextField(default=None, help_text='Public eligibility summary if provided by user.', null=True),
        ),
    ]
