# Generated by Django 2.2.13 on 2020-07-27 10:45

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0064_auto_20200723_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalbarrierinstance',
            name='commodities_cache',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), default=list, size=None),
        ),
    ]
