# Generated by Django 2.2.13 on 2020-06-30 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0066_auto_20200629_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barrierinstance',
            options={'ordering': ['-reported_on'], 'permissions': [('change_barrier_public_eligibility', 'Can change barrier public eligibility')]},
        ),
        migrations.AlterModelOptions(
            name='publicbarrier',
            options={'permissions': [('publish_barrier', 'Can publish barrier'), ('mark_barrier_as_ready_for_publishing', 'Can mark barrier as ready for publishing')]},
        ),
    ]
