# Generated by Django 2.2.13 on 2020-07-06 08:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0068_public_barrier_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpublicbarrier",
            name="categories_cache",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=20),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
