# Generated by Django 2.2.12 on 2020-07-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0069_historicalpublicbarrier_categories_cache"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalpublicbarrier",
            old_name="summary",
            new_name="_summary",
        ),
        migrations.RenameField(
            model_name="historicalpublicbarrier",
            old_name="title",
            new_name="_title",
        ),
        migrations.RenameField(
            model_name="publicbarrier",
            old_name="summary",
            new_name="_summary",
        ),
        migrations.RenameField(
            model_name="publicbarrier",
            old_name="title",
            new_name="_title",
        ),
        migrations.AddField(
            model_name="historicalpublicbarrier",
            name="summary_updated_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalpublicbarrier",
            name="title_updated_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publicbarrier",
            name="summary_updated_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publicbarrier",
            name="title_updated_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalpublicbarrier",
            name="all_sectors",
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name="publicbarrier",
            name="all_sectors",
            field=models.NullBooleanField(),
        ),
    ]
