# Generated by Django 2.2.12 on 2020-07-10 23:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0071_auto_20200709_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpublicbarrier',
            name='published_versions',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='publicbarrier',
            name='published_versions',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
