# Generated by Django 2.2.12 on 2020-07-16 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0073_auto_20200713_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicbarrier',
            name='barrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_barriers', to='barriers.BarrierInstance'),
        ),
    ]
