# Generated by Django 2.2.13 on 2020-07-31 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0077_auto_20200730_1042"),
        ("barriers", "0064_barrier_commodities"),
    ]

    operations = []
