# Generated by Django 2.2.13 on 2020-08-04 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0078_merge_20200731_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrierinstance',
            name='priority',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='barrier', to='metadata.BarrierPriority'),
        ),
        migrations.AlterField(
            model_name='historicalbarrierinstance',
            name='priority',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='metadata.BarrierPriority'),
        ),
    ]
