# Generated by Django 2.2.13 on 2020-08-04 10:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0079_auto_20200804_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrierinstance',
            name='country_admin_areas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, help_text='list of states, provinces, regions etc within a country', size=None),
        ),
        migrations.AlterField(
            model_name='historicalbarrierinstance',
            name='country_admin_areas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, help_text='list of states, provinces, regions etc within a country', size=None),
        ),
    ]
