# Generated by Django 2.2.13 on 2020-08-06 13:33

from django.db import migrations


def populate_historical_priority(apps, schema_editor):
    HistoricalBarrierInstance = apps.get_model("barriers", "HistoricalBarrierInstance")
    HistoricalBarrierInstance.objects.filter(
        priority__isnull=True
    ).update(priority=1)


class Migration(migrations.Migration):
    dependencies = [
        ('barriers', '0079_auto_20200806_1333'),
    ]

    operations = [
        migrations.RunPython(
            populate_historical_priority,
            reverse_code=migrations.RunPython.noop
        ),
    ]
