# Generated by Django 2.2.12 on 2020-08-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0083_auto_20200812_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrierinstance',
            name='trade_direction',
            field=models.SmallIntegerField(choices=[(1, 'Exporting from the UK or investing overseas'), (2, 'Importing or investing into the UK')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbarrierinstance',
            name='trade_direction',
            field=models.SmallIntegerField(choices=[(1, 'Exporting from the UK or investing overseas'), (2, 'Importing or investing into the UK')], default=None, null=True),
        ),
    ]
