# Generated by Django 3.1.1 on 2020-09-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0087_auto_20200901_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpublicbarrier',
            name='caused_by_trading_bloc',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='publicbarrier',
            name='caused_by_trading_bloc',
            field=models.BooleanField(null=True),
        ),
    ]
