# Generated by Django 3.1.1 on 2020-09-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0088_auto_20200903_1509"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpublicbarrier",
            name="caused_by_trading_bloc",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="publicbarrier",
            name="caused_by_trading_bloc",
            field=models.BooleanField(null=True),
        ),
    ]
