# Generated by Django 3.1.1 on 2020-09-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0089_auto_20200915_1458"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpublicbarrier",
            name="status_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="publicbarrier",
            name="status_date",
            field=models.DateField(null=True),
        ),
    ]
