# Generated by Django 3.1.2 on 2020-11-02 16:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wto', '0007_auto_20200901_1511'),
        ('assessment', '0010_auto_20201102_0943'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commodities', '0002_auto_20200723_1020'),
        ('collaboration', '0005_team_members_overhaul'),
        ('interactions', '0009_auto_20200901_1511'),
        ('metadata', '0015_nip_tag'),
        ('history', '0002_rename_public_barrier_country_to_location'),
        ('barriers', '0093_auto_20201102_1558'),
        ('user', '0017_assessment_permissions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BarrierInstance',
            new_name='Barrier',
        ),
        migrations.RenameModel(
            old_name='HistoricalBarrierInstance',
            new_name='HistoricalBarrier',
        ),
        migrations.AlterModelOptions(
            name='historicalbarrier',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical barrier'},
        ),
    ]
