# Generated by Django 3.1.2 on 2020-11-05 17:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0015_nip_tag"),
        ("barriers", "0095_convert_null_to_empty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barrier",
            name="all_sectors",
            field=models.BooleanField(
                blank=True, help_text="Does the barrier affect all sectors?", null=True
            ),
        ),
        migrations.AlterField(
            model_name="barrier",
            name="archived_explanation",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="barrier",
            name="archived_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DUPLICATE", "Duplicate"),
                    ("NOT_A_BARRIER", "Not a barrier"),
                    ("OTHER", "Other"),
                ],
                default="",
                max_length=25,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="barrier",
            name="categories",
            field=models.ManyToManyField(
                related_name="barriers", to="metadata.Category"
            ),
        ),
        migrations.AlterField(
            model_name="barrier",
            name="code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Readable reference code e.g. B-20-NTZ",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="barrier",
            name="companies",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="barrier",
            name="country",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="barrier",
            name="end_date",
            field=models.DateField(
                blank=True, help_text="Date the barrier ends", null=True
            ),
        ),
        migrations.AlterField(
            model_name="barrier",
            name="is_summary_sensitive",
            field=models.BooleanField(
                blank=True,
                help_text="Does the summary contain sensitive information?",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="barrier",
            name="next_steps_summary",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="barrier",
            name="other_source",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="barrier",
            name="priority_date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="barrier",
            name="priority_summary",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="barrier",
            name="product",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="barrier",
            name="public_eligibility",
            field=models.BooleanField(
                blank=True,
                help_text="Mark the barrier as either publishable or unpublishable to the public.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="barrier",
            name="sectors",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(), blank=True, default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="barrier",
            name="sectors_affected",
            field=models.BooleanField(
                blank=True, help_text="Does the barrier affect any sectors?", null=True
            ),
        ),
        migrations.AlterField(
            model_name="barrier",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COMPANY", "Company"),
                    ("TRADE", "Trade association"),
                    ("GOVT", "Government entity"),
                    ("OTHER", "Other"),
                ],
                default="",
                max_length=25,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="barrier",
            name="status",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "Unfinished"),
                    (1, "Open: Pending action"),
                    (2, "Open: In progress"),
                    (3, "Resolved: In part"),
                    (4, "Resolved: In full"),
                    (5, "Dormant"),
                    (6, "Archived"),
                    (7, "Unknown"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="barrier",
            name="status_date",
            field=models.DateField(
                blank=True,
                help_text="If resolved or part-resolved, the month and year supplied by the user, otherwise the current time when the status was set.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="barrier",
            name="status_summary",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="barrier",
            name="sub_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UK_GOVT", "UK government"),
                    ("FOR_GOVT", "Foreign government"),
                    ("BUS", "Affected business"),
                    ("OTHER", "Other"),
                ],
                default="",
                max_length=25,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="barrier",
            name="sub_status_other",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Text if sub status is 'OTHER'",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="barrier",
            name="summary",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="barrier",
            name="term",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "A procedural, short-term barrier"),
                    (2, "A long-term strategic barrier"),
                ],
                help_text="Is this a short-term procedural or long-term strategic barrier?",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="barrier",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="barrier",
            name="trade_direction",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, "Exporting from the UK or investing overseas"),
                    (2, "Importing or investing into the UK"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="barrier",
            name="trading_bloc",
            field=models.CharField(
                blank=True,
                choices=[("TB00016", "European Union")],
                default="",
                max_length=7,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="barrier",
            name="unarchived_reason",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="barriercommodity",
            name="country",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="barriercommodity",
            name="trading_bloc",
            field=models.CharField(blank=True, choices=[], default="", max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="barrierreportstage",
            name="status",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "NOT STARTED"), (2, "IN PROGRESS"), (3, "COMPLETED")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbarrier",
            name="all_sectors",
            field=models.BooleanField(
                blank=True, help_text="Does the barrier affect all sectors?", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalbarrier",
            name="archived_explanation",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalbarrier",
            name="archived_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DUPLICATE", "Duplicate"),
                    ("NOT_A_BARRIER", "Not a barrier"),
                    ("OTHER", "Other"),
                ],
                default="",
                max_length=25,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalbarrier",
            name="categories_cache",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbarrier",
            name="code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Readable reference code e.g. B-20-NTZ",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbarrier",
            name="commodities_cache",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(), blank=True, default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="historicalbarrier",
            name="companies",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalbarrier",
            name="country",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalbarrier",
            name="end_date",
            field=models.DateField(
                blank=True, help_text="Date the barrier ends", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalbarrier",
            name="is_summary_sensitive",
            field=models.BooleanField(
                blank=True,
                help_text="Does the summary contain sensitive information?",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbarrier",
            name="next_steps_summary",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalbarrier",
            name="other_source",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalbarrier",
            name="priority_date",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="historicalbarrier",
            name="priority_summary",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalbarrier",
            name="product",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalbarrier",
            name="public_eligibility",
            field=models.BooleanField(
                blank=True,
                help_text="Mark the barrier as either publishable or unpublishable to the public.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbarrier",
            name="sectors",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(), blank=True, default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="historicalbarrier",
            name="sectors_affected",
            field=models.BooleanField(
                blank=True, help_text="Does the barrier affect any sectors?", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalbarrier",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COMPANY", "Company"),
                    ("TRADE", "Trade association"),
                    ("GOVT", "Government entity"),
                    ("OTHER", "Other"),
                ],
                default="",
                max_length=25,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalbarrier",
            name="status",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "Unfinished"),
                    (1, "Open: Pending action"),
                    (2, "Open: In progress"),
                    (3, "Resolved: In part"),
                    (4, "Resolved: In full"),
                    (5, "Dormant"),
                    (6, "Archived"),
                    (7, "Unknown"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbarrier",
            name="status_date",
            field=models.DateField(
                blank=True,
                help_text="If resolved or part-resolved, the month and year supplied by the user, otherwise the current time when the status was set.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbarrier",
            name="status_summary",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalbarrier",
            name="sub_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UK_GOVT", "UK government"),
                    ("FOR_GOVT", "Foreign government"),
                    ("BUS", "Affected business"),
                    ("OTHER", "Other"),
                ],
                default="",
                max_length=25,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalbarrier",
            name="sub_status_other",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Text if sub status is 'OTHER'",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalbarrier",
            name="summary",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalbarrier",
            name="tags_cache",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="historicalbarrier",
            name="term",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "A procedural, short-term barrier"),
                    (2, "A long-term strategic barrier"),
                ],
                help_text="Is this a short-term procedural or long-term strategic barrier?",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbarrier",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalbarrier",
            name="trade_direction",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, "Exporting from the UK or investing overseas"),
                    (2, "Importing or investing into the UK"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbarrier",
            name="trading_bloc",
            field=models.CharField(
                blank=True,
                choices=[("TB00016", "European Union")],
                default="",
                max_length=7,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalbarrier",
            name="unarchived_reason",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalbarrierreportstage",
            name="status",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[(1, "NOT STARTED"), (2, "IN PROGRESS"), (3, "COMPLETED")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalpublicbarrier",
            name="_summary",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalpublicbarrier",
            name="_title",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalpublicbarrier",
            name="all_sectors",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalpublicbarrier",
            name="archived_reason",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalpublicbarrier",
            name="categories_cache",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=20),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="historicalpublicbarrier",
            name="caused_by_trading_bloc",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalpublicbarrier",
            name="country",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalpublicbarrier",
            name="internal_summary_at_update",
            field=models.TextField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalpublicbarrier",
            name="internal_title_at_update",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalpublicbarrier",
            name="status_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalpublicbarrier",
            name="trading_bloc",
            field=models.CharField(blank=True, choices=[], default="", max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalpublicbarrier",
            name="unarchived_reason",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="publicbarrier",
            name="_summary",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="publicbarrier",
            name="_title",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="publicbarrier",
            name="all_sectors",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="publicbarrier",
            name="archived_reason",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="publicbarrier",
            name="caused_by_trading_bloc",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="publicbarrier",
            name="country",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="publicbarrier",
            name="internal_summary_at_update",
            field=models.TextField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="publicbarrier",
            name="internal_title_at_update",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="publicbarrier",
            name="status_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="publicbarrier",
            name="trading_bloc",
            field=models.CharField(blank=True, choices=[], default="", max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="publicbarrier",
            name="unarchived_reason",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
