# Generated by Django 3.1.2 on 2020-11-18 12:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0097_barrier_organisations"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalbarrier",
            name="organisations_cache",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, default=list, size=None
            ),
        ),
    ]
