# Generated by Django 3.1.2 on 2020-11-24 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0099_populate_commercial_value"),
        ("barriers", "0098_historicalbarrier_organisations_cache"),
    ]

    operations = []
