# Generated by Django 3.1.2 on 2020-12-21 18:17

from django.db import migrations, models
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0100_merge_20201124_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpublicbarrier',
            name='id',
            field=models.IntegerField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='publicbarrier',
            name='id',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=8, primary_key=True, serialize=False),
        ),
    ]
