# Generated by Django 3.1.8 on 2021-04-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0103_auto_20210407_1012"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barrier",
            name="trading_bloc",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TB00016", "European Union (EU)"),
                    ("TB00017", "Gulf Cooperation Council (GCC)"),
                    ("TB00013", "Eurasian Economic Union (EAEU)"),
                    ("TB00026", "Southern Common Market (Mercosur)"),
                ],
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbarrier",
            name="trading_bloc",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TB00016", "European Union (EU)"),
                    ("TB00017", "Gulf Cooperation Council (GCC)"),
                    ("TB00013", "Eurasian Economic Union (EAEU)"),
                    ("TB00026", "Southern Common Market (Mercosur)"),
                ],
                max_length=7,
            ),
        ),
    ]
