# Generated by Django 3.1.8 on 2021-04-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0104_auto_20210415_0836"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpublicbarrier",
            name="_public_view_status",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "Not yet sifted"),
                    (10, "Not allowed"),
                    (20, "Allowed"),
                    (30, "Ready"),
                    (40, "Published"),
                    (50, "Unpublished"),
                    (60, "Review later"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="publicbarrier",
            name="_public_view_status",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "Not yet sifted"),
                    (10, "Not allowed"),
                    (20, "Allowed"),
                    (30, "Ready"),
                    (40, "Published"),
                    (50, "Unpublished"),
                    (60, "Review later"),
                ],
                default=0,
            ),
        ),
    ]
