# Generated by Django 3.1.8 on 2021-04-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0105_auto_20210416_1219"),
    ]

    operations = [
        migrations.AddField(
            model_name="barrier",
            name="public_eligibility_postponed",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="If public eligibility has been marked to be reviewed later.",
            ),
        ),
        migrations.AddField(
            model_name="historicalbarrier",
            name="public_eligibility_postponed",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="If public eligibility has been marked to be reviewed later.",
            ),
        ),
    ]
