# Generated by Django 3.2.7 on 2021-11-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0109_publicbarrierlighttouchreviews_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicbarrierlighttouchreviews',
            name='hm_trade_commissioner_approval_enabled',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
