# Generated by Django 3.2.7 on 2021-11-18 08:28

from django.db import migrations


def set_hm_trade_commissioner_enabled_by_default(apps, schema_editor):
    PublicBarrierLightTouchReviews = apps.get_model(
        "barriers", "PublicBarrierLightTouchReviews"
    )
    PublicBarrierLightTouchReviews.objects.update(
        hm_trade_commissioner_approval_enabled=True
    )


class Migration(migrations.Migration):

    dependencies = [
        (
            "barriers",
            "0110_alter_publicbarrierlighttouchreviews_hm_trade_commissioner_approval_enabled",
        ),
    ]

    operations = [
        migrations.RunPython(
            set_hm_trade_commissioner_enabled_by_default,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
