# Generated by Django 3.2.7 on 2021-11-26 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0112_barrierrequestdownloadapproval_barriersearchcsvdownloadevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barrier',
            options={'ordering': ['-reported_on'], 'permissions': [('change_barrier_public_eligibility', 'Can change barrier public eligibility'), ('download_barriers', 'Can download barriers')]},
        ),
    ]
