# Generated by Django 3.2.7 on 2022-01-11 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0114_auto_20211126_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barriersearchcsvdownloadevent',
            name='barrier_ids',
            field=models.TextField(validators=[django.core.validators.int_list_validator]),
        ),
    ]
