# Generated by Django 3.2.7 on 2022-03-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0115_alter_barriersearchcsvdownloadevent_barrier_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="barrier",
            name="next_steps",
            field=models.TextField(
                blank=True,
                help_text="What next steps are required to address the barrier?",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="barrier",
            name="progress_update",
            field=models.TextField(
                blank=True,
                help_text="What has been done to address the barrier?",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalbarrier",
            name="next_steps",
            field=models.TextField(
                blank=True,
                help_text="What next steps are required to address the barrier?",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalbarrier",
            name="progress_update",
            field=models.TextField(
                blank=True,
                help_text="What has been done to address the barrier?",
                null=True,
            ),
        ),
    ]
