# Generated by Django 3.2.7 on 2022-02-14 14:14

from django.db import migrations


# create new Category with title of "Import controls" a description of "" and category of "GOODS"
def add_import_controls_category(apps, schema_editor):
    Category = apps.get_model("barriers", "Category")
    Category.objects.create(title="Import controls", description="", category="GOODS")


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0115_alter_barriersearchcsvdownloadevent_barrier_ids"),
    ]

    operations = [
        migrations.RunPython(
            add_import_controls_category, reverse_code=migrations.RunPython.noop
        ),
    ]
