# Generated by Django 3.2.7 on 2022-03-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0117_auto_20220304_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrier',
            name='progress_status',
            field=models.CharField(choices=[('ON_TRACK', 'On track'), ('RISK_OF_DELAY', 'Risk of delay'), ('DELAYED', 'Delayed')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalbarrier',
            name='progress_status',
            field=models.CharField(choices=[('ON_TRACK', 'On track'), ('RISK_OF_DELAY', 'Risk of delay'), ('DELAYED', 'Delayed')], max_length=100, null=True),
        ),
    ]
