# Generated by Django 3.2.7 on 2022-03-17 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0118_barrierprogressupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barrier',
            name='next_steps',
        ),
        migrations.RemoveField(
            model_name='barrier',
            name='progress_status',
        ),
        migrations.RemoveField(
            model_name='barrier',
            name='progress_update',
        ),
        migrations.RemoveField(
            model_name='historicalbarrier',
            name='next_steps',
        ),
        migrations.RemoveField(
            model_name='historicalbarrier',
            name='progress_status',
        ),
        migrations.RemoveField(
            model_name='historicalbarrier',
            name='progress_update',
        ),
    ]
