# Generated by Django 3.2.7 on 2022-03-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0119_auto_20220317_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrierprogressupdate',
            name='created_on',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='barrierprogressupdate',
            name='modified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
