# Generated by Django 3.2.12 on 2022-03-25 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0120_auto_20220318_1424"),
    ]

    operations = [
        migrations.RenameField(
            model_name="barrier",
            old_name="end_date",
            new_name="estimated_resolution_date",
        ),
        migrations.RenameField(
            model_name="historicalbarrier",
            old_name="end_date",
            new_name="estimated_resolution_date",
        ),
    ]
