# Generated by Django 3.2.7 on 2022-04-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0121_auto_20220325_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrier',
            name='activity_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbarrier',
            name='activity_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
