# Generated by Django 3.2.12 on 2022-04-01 13:46

from django.db import migrations, models

import logging

logger = logging.getLogger(__name__)


def set_current_barrier_completion_percentages(apps, schema_editor):
    # We need to calculate the completion % of all existing barriers,
    # or the frontend will display 0% (or more likely trigger a null error)
    # for a barrier until it is updated

    # Get all current barriers
    Barrier = apps.get_model("barriers", "Barrier")
    barrier_list = Barrier.objects.all()

    # Loop through each barrier
    for barrier in barrier_list:

        # work out the % completed
        total = 0
        if barrier.country or barrier.trading_bloc:
            # There has been a location indicated
            total += 18
        if barrier.summary:
            total += 18
        if barrier.source:
            total += 16
        if barrier.sectors:
            total += 16
        if barrier.categories.all().count() > 0:
            total += 16
        if barrier.commodities.all().count() > 0:
            total += 16

        # Set its completed % value
        Barrier.objects.filter(pk=barrier.pk).update(completion_percent=total)


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0122_auto_20220401_1101"),
    ]

    operations = [
        migrations.AddField(
            model_name="barrier",
            name="completion_percent",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Percentage value representing how much information regarding a barrier has been provided",
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalbarrier",
            name="completion_percent",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Percentage value representing how much information regarding a barrier has been provided",
                max_length=3,
                null=True,
            ),
        ),
        migrations.RunPython(
            set_current_barrier_completion_percentages,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
