# Generated by Django 3.2.13 on 2022-05-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0024_barriertag_is_top_priority_tag"),
        ("barriers", "0125_auto_20220511_0941"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barrier",
            name="tags",
            field=models.ManyToManyField(blank=True, to="metadata.BarrierTag"),
        ),
    ]
