# Generated by Django 3.2.12 on 2022-05-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0126_alter_barrier_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrier',
            name='top_priority_rejection_summary',
            field=models.TextField(blank=True, help_text='If an admin rejects a request for top priority, this is the message that will be displayed to the user.', null=True),
        ),
        migrations.AddField(
            model_name='historicalbarrier',
            name='top_priority_rejection_summary',
            field=models.TextField(blank=True, help_text='If an admin rejects a request for top priority, this is the message that will be displayed to the user.', null=True),
        ),
    ]
