# Generated by Django 3.2.14 on 2022-08-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0128_update_companies_to_be_compatible_with_ch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barrier",
            name="top_priority_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NONE", ""),
                    ("APPROVAL_PENDING", "Top 100 Priority Barrier - Approval Pending"),
                    ("REMOVAL_PENDING", "Top 100 Priority Barrier - Removal Pending"),
                    ("APPROVED", "Top 100 Priority Barrier"),
                    ("RESOLVED", "Top 100 Priority Barrier - Resolved"),
                ],
                default="NONE",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbarrier",
            name="top_priority_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NONE", ""),
                    ("APPROVAL_PENDING", "Top 100 Priority Barrier - Approval Pending"),
                    ("REMOVAL_PENDING", "Top 100 Priority Barrier - Removal Pending"),
                    ("APPROVED", "Top 100 Priority Barrier"),
                    ("RESOLVED", "Top 100 Priority Barrier - Resolved"),
                ],
                default="NONE",
                max_length=50,
            ),
        ),
    ]
