# Generated by Django 3.2.13 on 2022-07-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0129_auto_20220810_1303"),
    ]

    operations = [
        migrations.AddField(
            model_name="barrier",
            name="caused_by_admin_areas",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalbarrier",
            name="caused_by_admin_areas",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
