# Generated by Django 3.2.15 on 2022-09-09 10:25

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("barriers", "0130_auto_20220706_0943"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="barrierprogressupdate",
            options={
                "ordering": ("-created_on",),
                "verbose_name": "Top 100 Barrier Progress Update",
                "verbose_name_plural": "Top 100 Barrier Progress Updates",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalbarrierprogressupdate",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Top 100 Barrier Progress Update",
            },
        ),
        migrations.CreateModel(
            name="ProgrammeFundProgressUpdate",
            fields=[
                ("archived", models.BooleanField(default=False)),
                ("archived_on", models.DateTimeField(blank=True, null=True)),
                ("archived_reason", models.TextField(blank=True)),
                ("unarchived_reason", models.TextField(blank=True)),
                ("unarchived_on", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "milestones_and_deliverables",
                    models.TextField(
                        blank=True,
                        help_text="What has been done to address the barrier?",
                        null=True,
                    ),
                ),
                (
                    "expenditure",
                    models.TextField(
                        blank=True,
                        help_text="What next steps are required to address the barrier?",
                        null=True,
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "barrier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programme_fund_progress_updates",
                        to="barriers.barrier",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unarchived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Programme Fund Barrier Progress Update",
                "verbose_name_plural": "Programme Fund Barrier Progress Updates",
                "ordering": ("-created_on",),
            },
        ),
        migrations.CreateModel(
            name="HistoricalProgrammeFundProgressUpdate",
            fields=[
                ("archived", models.BooleanField(default=False)),
                ("archived_on", models.DateTimeField(blank=True, null=True)),
                ("archived_reason", models.TextField(blank=True)),
                ("unarchived_reason", models.TextField(blank=True)),
                ("unarchived_on", models.DateTimeField(blank=True, null=True)),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                (
                    "created_on",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("modified_on", models.DateTimeField(blank=True, null=True)),
                (
                    "milestones_and_deliverables",
                    models.TextField(
                        blank=True,
                        help_text="What has been done to address the barrier?",
                        null=True,
                    ),
                ),
                (
                    "expenditure",
                    models.TextField(
                        blank=True,
                        help_text="What next steps are required to address the barrier?",
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "barrier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="barriers.barrier",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unarchived_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Programme Fund Barrier Progress Update",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
