# Generated by Django 3.2.15 on 2022-10-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0131_auto_20220909_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrier',
            name='priority_level',
            field=models.CharField(blank=True, choices=[('NONE', ''), ('REGIONAL', 'Regional Priority'), ('COUNTRY', 'Country Priority'), ('WATCHLIST', 'Watch list')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalbarrier',
            name='priority_level',
            field=models.CharField(blank=True, choices=[('NONE', ''), ('REGIONAL', 'Regional Priority'), ('COUNTRY', 'Country Priority'), ('WATCHLIST', 'Watch list')], default='NONE', max_length=20),
        ),
    ]
