# Generated by Django 3.2.15 on 2022-11-18 11:49

from django.db import migrations


def migrate_barrier_status_open_pending_to_open_in_progress(apps, schema_editor):
    OPEN_PENDING_ID = 1
    OPEN_IN_PROGRESS_ID = 2
    Barrier = apps.get_model("barriers", "Barrier")
    open_pending_barriers = Barrier.objects.filter(status=OPEN_PENDING_ID)
    open_pending_barriers.update(status=OPEN_IN_PROGRESS_ID)


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0132_auto_20221021_1052"),
    ]

    operations = [
        migrations.RunPython(migrate_barrier_status_open_pending_to_open_in_progress),
    ]
