# Generated by Django 3.2.15 on 2022-11-21 12:17

from django.db import migrations


def migrate_uknown_barriers_to_open_status_migration(apps, schema_editor):
    Barrier = apps.get_model("barriers", "Barrier")
    UKNOWN_STATUS = 7
    OPEN_STATUS = 2
    unknown_barriers = Barrier.objects.filter(status=UKNOWN_STATUS)
    # update the status of the barriers to open
    unknown_barriers.update(status=OPEN_STATUS)


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0133_migrate_open_status"),
    ]

    operations = [
        migrations.RunPython(migrate_uknown_barriers_to_open_status_migration),
    ]
