# Generated by Django 3.2.16 on 2022-12-02 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barriers', '0134_migrate_unknown_barriers_to_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrier',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Unfinished'), (1, 'Open'), (2, 'Open'), (3, 'Resolved: In part'), (4, 'Resolved: In full'), (5, 'Dormant'), (6, 'Archived'), (7, 'Unknown')], default=0),
        ),
        migrations.AlterField(
            model_name='historicalbarrier',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Unfinished'), (1, 'Open'), (2, 'Open'), (3, 'Resolved: In part'), (4, 'Resolved: In full'), (5, 'Dormant'), (6, 'Archived'), (7, 'Unknown')], default=0),
        ),
        migrations.AlterField(
            model_name='historicalpublicbarrier',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Unfinished'), (1, 'Open'), (2, 'Open'), (3, 'Resolved: In part'), (4, 'Resolved: In full'), (5, 'Dormant'), (6, 'Archived'), (7, 'Unknown')], default=0),
        ),
        migrations.AlterField(
            model_name='publicbarrier',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Unfinished'), (1, 'Open'), (2, 'Open'), (3, 'Resolved: In part'), (4, 'Resolved: In full'), (5, 'Dormant'), (6, 'Archived'), (7, 'Unknown')], default=0),
        ),
        migrations.CreateModel(
            name='BarrierPriorityHistoricalSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('top_priority_status', models.CharField(blank=True, max_length=50, null=True)),
                ('top_priority_rejection_summary', models.TextField(blank=True, null=True)),
                ('top_priority_summary', models.TextField(blank=True, null=True)),
                ('barrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority_historical_summaries', to='barriers.barrier')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_barrier_priorities', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_barrier_priorities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
