# Generated by Django 3.2.16 on 2022-12-02 14:33

from django.db import migrations


def populate_summaries_table_from_history(apps, schema_editor):
    Barrier = apps.get_model("barriers", "Barrier")
    HistoricalBarrier = apps.get_model("barriers", "HistoricalBarrier")

    BarrierTopPrioritySummary = apps.get_model("barriers", "BarrierTopPrioritySummary")

    # Get and loop through every barrier
    for barrier in Barrier.objects.all():
        # Get the historical changes of the barrier which contain priority summary
        history_items = (
            HistoricalBarrier.objects.filter(id=barrier.id)
            .order_by("-created_on")
            .all()
            .exclude(priority_summary__exact='')
        )

        # Perform next section if the barrier has had a priority_summary at some point
        if history_items.count() > 0:

            # Get the earliest appearence of the priority_summary and the latest
            first_update = history_items.first()
            last_update = history_items.last()

            # If the first update text matches the last update text, we can use
            # the creation_date as modified_date
            if first_update.priority_summary == last_update.priority_summary:
                new_summary = BarrierTopPrioritySummary(
                    barrier=barrier,
                    created_by=first_update.user,
                    created_on=first_update.history_date,
                    modified_by=first_update.user,
                    modified_on=first_update.history_date,
                    top_priority_summary_text=last_update.priority_summary
                )
                new_summary.save()
            else:
                new_summary = BarrierTopPrioritySummary(
                    barrier=barrier,
                    created_by=first_update.user,
                    created_on=first_update.history_date,
                    modified_by=last_update.user,
                    modified_on=last_update.history_date,
                    top_priority_summary_text=last_update.priority_summary
                )
                new_summary.save()


def revert_populate_summaries_table_from_history(apps, schema_editor):
    BarrierTopPrioritySummary = apps.get_model("barriers", "BarrierTopPrioritySummary")
    BarrierTopPrioritySummary.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0135_barriertopprioritysummary"),
    ]

    operations = [
        migrations.RunPython(
            populate_summaries_table_from_history,
            revert_populate_summaries_table_from_history,
        ),
    ]
