# Generated by Django 3.2.16 on 2023-02-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0136_populate_priority_summaries_from_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrier',
            name='proposed_estimated_resolution_date',
            field=models.DateField(blank=True, help_text='Date the barrier ends', null=True),
        ),
        migrations.AddField(
            model_name='historicalbarrier',
            name='proposed_estimated_resolution_date',
            field=models.DateField(blank=True, help_text='Date the barrier ends', null=True),
        ),
        migrations.AlterField(
            model_name='barrier',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Unfinished'), (1, 'Open'), (2, 'Open'), (3, 'Resolved: In part'), (4, 'Resolved: In full'), (5, 'Dormant'), (6, 'Archived'), (7, 'Unknown')], default=0),
        ),
        migrations.AlterField(
            model_name='barrier',
            name='top_priority_status',
            field=models.CharField(blank=True, choices=[('NONE', ''), ('APPROVAL_PENDING', 'Top 100 Approval Pending'), ('REMOVAL_PENDING', 'Top 100 Removal Pending'), ('APPROVED', 'Top 100 Priority'), ('RESOLVED', 'Resolved Top 100 Priority')], default='NONE', max_length=50),
        ),
        migrations.AlterField(
            model_name='barriertopprioritysummary',
            name='top_priority_summary_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='historicalbarrier',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Unfinished'), (1, 'Open'), (2, 'Open'), (3, 'Resolved: In part'), (4, 'Resolved: In full'), (5, 'Dormant'), (6, 'Archived'), (7, 'Unknown')], default=0),
        ),
        migrations.AlterField(
            model_name='historicalbarrier',
            name='top_priority_status',
            field=models.CharField(blank=True, choices=[('NONE', ''), ('APPROVAL_PENDING', 'Top 100 Approval Pending'), ('REMOVAL_PENDING', 'Top 100 Removal Pending'), ('APPROVED', 'Top 100 Priority'), ('RESOLVED', 'Resolved Top 100 Priority')], default='NONE', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalpublicbarrier',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Unfinished'), (1, 'Open'), (2, 'Open'), (3, 'Resolved: In part'), (4, 'Resolved: In full'), (5, 'Dormant'), (6, 'Archived'), (7, 'Unknown')], default=0),
        ),
        migrations.AlterField(
            model_name='publicbarrier',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Unfinished'), (1, 'Open'), (2, 'Open'), (3, 'Resolved: In part'), (4, 'Resolved: In full'), (5, 'Dormant'), (6, 'Archived'), (7, 'Unknown')], default=0),
        ),
    ]
