# Generated by Django 3.2.16 on 2023-02-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0138_permissions_for_est_date_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrier',
            name='estimated_resolution_date_change_reason',
            field=models.TextField(blank=True, help_text='Reason for proposed date', null=True),
        ),
        migrations.AddField(
            model_name='historicalbarrier',
            name='estimated_resolution_date_change_reason',
            field=models.TextField(blank=True, help_text='Reason for proposed date', null=True),
        ),
    ]
