# Generated by Django 3.2.16 on 2023-02-10 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barriers', '0140_auto_20230210_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrier',
            name='proposed_estimated_resolution_date_created',
            field=models.DateTimeField(blank=True, help_text='Date in which the proposed date was created', null=True),
        ),
        migrations.AddField(
            model_name='historicalbarrier',
            name='proposed_estimated_resolution_date_created',
            field=models.DateTimeField(blank=True, help_text='Date in which the proposed date was created', null=True),
        ),
        migrations.AlterField(
            model_name='barrier',
            name='proposed_estimated_resolution_date',
            field=models.DateField(blank=True, help_text='Proposed date the barrier ends', null=True),
        ),
        migrations.AlterField(
            model_name='barrier',
            name='proposed_estimated_resolution_date_user',
            field=models.ForeignKey(blank=True, help_text='User who created the proposed date', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_estimated_resolution_date_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalbarrier',
            name='proposed_estimated_resolution_date',
            field=models.DateField(blank=True, help_text='Proposed date the barrier ends', null=True),
        ),
        migrations.AlterField(
            model_name='historicalbarrier',
            name='proposed_estimated_resolution_date_user',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who created the proposed date', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
