# Generated by Django 3.2.18 on 2023-05-10 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0142_barriernextstepitem_historicalbarriernextstepitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="barrier",
            name="public_barrier_summary",
            field=models.TextField(
                blank=True,
                help_text="Public summary of the barrier if provided by user.",
            ),
        ),
        migrations.AddField(
            model_name="historicalbarrier",
            name="public_barrier_summary",
            field=models.TextField(
                blank=True,
                help_text="Public summary of the barrier if provided by user.",
            ),
        ),
        migrations.AlterField(
            model_name="barriernextstepitem",
            name="barrier",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="next_steps_items",
                to="barriers.barrier",
            ),
        ),
        migrations.AlterField(
            model_name="barriernextstepitem",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NOT_STARTED", "Not started"),
                    ("IN_PROGRESS", "In progress"),
                    ("COMPLETED", "Completed"),
                ],
                default="IN_PROGRESS",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbarriernextstepitem",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NOT_STARTED", "Not started"),
                    ("IN_PROGRESS", "In progress"),
                    ("COMPLETED", "Completed"),
                ],
                default="IN_PROGRESS",
                max_length=15,
            ),
        ),
    ]
