# Generated by Django 3.2.18 on 2023-05-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0143_auto_20230512_1026"),
    ]

    operations = [
        migrations.AddField(
            model_name="barrier",
            name="new_report_session_data",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalbarrier",
            name="new_report_session_data",
            field=models.TextField(blank=True),
        ),
    ]
