# Generated by Django 3.2.18 on 2023-05-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0144_auto_20230512_1636"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barrier",
            name="new_report_session_data",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalbarrier",
            name="new_report_session_data",
            field=models.TextField(blank=True, null=True),
        ),
    ]
