# Generated by Django 3.2.19 on 2023-06-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0034_exporttype"),
        ("barriers", "0144_auto_20230512_1636"),
    ]

    operations = [
        migrations.AddField(
            model_name="barrier",
            name="export_types",
            field=models.ManyToManyField(
                related_name="barriers", to="metadata.ExportType"
            ),
        ),
        migrations.AddField(
            model_name="barrier",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalbarrier",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
