# Generated by Django 3.2.19 on 2023-06-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0145_auto_20230620_0843"),
    ]

    operations = [
        migrations.AddField(
            model_name="barrier",
            name="is_currently_active",
            field=models.BooleanField(
                blank=True,
                help_text="Is the barrier currently affecting trade?",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalbarrier",
            name="is_currently_active",
            field=models.BooleanField(
                blank=True,
                help_text="Is the barrier currently affecting trade?",
                null=True,
            ),
        ),
    ]
