# Generated by Django 3.2.19 on 2023-06-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0034_exporttype"),
        ("barriers", "0145_auto_20230620_1208"),
    ]

    operations = [
        migrations.AddField(
            model_name="barrier",
            name="export_types",
            field=models.ManyToManyField(blank=True, to="metadata.ExportType"),
        ),
    ]
