# Generated by Django 3.2.19 on 2023-06-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0146_barrier_export_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="barrier",
            name="is_currently_active",
            field=models.BooleanField(
                default=True, help_text="Is the barrier currently active"
            ),
        ),
        migrations.AddField(
            model_name="historicalbarrier",
            name="is_currently_active",
            field=models.BooleanField(
                default=True, help_text="Is the barrier currently active"
            ),
        ),
    ]
