# Generated by Django 3.2.19 on 2023-06-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0146_barrier_export_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="barrier",
            name="is_currently_active",
            field=models.BooleanField(
                help_text="Is the barrier currently active", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalbarrier",
            name="is_currently_active",
            field=models.BooleanField(
                help_text="Is the barrier currently active", null=True
            ),
        ),
    ]
