# Generated by Django 3.2.18 on 2023-06-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0147_auto_20230621_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrier',
            name='export_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='barrier',
            name='is_start_date_known',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='barrier',
            name='main_sector',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='barrier',
            name='related_organisations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbarrier',
            name='export_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbarrier',
            name='is_start_date_known',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalbarrier',
            name='main_sector',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbarrier',
            name='related_organisations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
