# Generated by Django 3.2.19 on 2023-08-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0148_auto_20230623_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrier',
            name='status_date',
            field=models.DateField(blank=True, help_text='If resolved or part-resolved, the month and year supplied by the user, otherwise the current time when the status was set. Records date status is effective from; resolved statuses are user-set, other statuses are effective immediately after the status change.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalbarrier',
            name='status_date',
            field=models.DateField(blank=True, help_text='If resolved or part-resolved, the month and year supplied by the user, otherwise the current time when the status was set. Records date status is effective from; resolved statuses are user-set, other statuses are effective immediately after the status change.', null=True),
        ),
    ]
