# Generated by Django 3.2.20 on 2023-09-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0150_historicalbarriertopprioritysummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalbarrier',
            name='top_priority_barrier_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
