# Generated by Django 3.2.20 on 2023-09-11 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0151_historicalbarrier_top_priority_barrier_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalbarrier',
            name='top_priority_barrier_summary',
        ),
    ]
