# Generated by Django 3.2.20 on 2023-09-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0152_remove_historicalbarrier_top_priority_barrier_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrier',
            name='priority_level',
            field=models.CharField(blank=True, choices=[('NONE', ''), ('OVERSEAS', 'Overseas Priority'), ('COUNTRY', 'Country Priority'), ('WATCHLIST', 'Watch list')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalbarrier',
            name='priority_level',
            field=models.CharField(blank=True, choices=[('NONE', ''), ('OVERSEAS', 'Overseas Priority'), ('COUNTRY', 'Country Priority'), ('WATCHLIST', 'Watch list')], default='NONE', max_length=20),
        ),
    ]
