# Generated by Django 3.2.20 on 2023-09-27 15:01

from django.db import migrations


def remove_priority_level_country_region_forwards_func(apps, schema_editor):
    Barrier = apps.get_model("barriers", "Barrier")
    db_alias = schema_editor.connection.alias
    Barrier.objects.using(db_alias).filter(
        top_priority_status="APPROVED", priority_level__in=["REGIONAL", "OVERSEAS"]
    ).update(priority_level="NONE")


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0152_remove_historicalbarrier_top_priority_barrier_summary"),
    ]

    operations = [
        migrations.RunPython(remove_priority_level_country_region_forwards_func)
    ]
