# Generated by Django 3.2.20 on 2023-09-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0153_auto_20230925_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrier',
            name='priority_level',
            field=models.CharField(blank=True, choices=[('NONE', ''), ('OVERSEAS', 'Overseas Delivery'), ('COUNTRY', 'Country Priority'), ('WATCHLIST', 'Watch list')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalbarrier',
            name='priority_level',
            field=models.CharField(blank=True, choices=[('NONE', ''), ('OVERSEAS', 'Overseas Delivery'), ('COUNTRY', 'Country Priority'), ('WATCHLIST', 'Watch list')], default='NONE', max_length=20),
        ),
    ]
