# Generated by Django 3.2.20 on 2023-09-29 09:56

from django.db import migrations

def update_saved_searches_to_overseas(apps, schema_editor):
    SavedSearch = apps.get_model("user", "SavedSearch")
    regional_saved_searches = SavedSearch.objects.filter(filters__priority_level__contains="REGIONAL")
    for saved_search in regional_saved_searches:
        new_priority_level = [each if each != "REGIONAL" else "OVERSEAS" for each in saved_search.filters["priority_level"]]
        saved_search.filters["priority_level"] = new_priority_level
        saved_search.save()

def update_saved_searches_to_regional(apps, schema_editor):
    SavedSearch = apps.get_model("user", "SavedSearch")
    regional_saved_searches = SavedSearch.objects.filter(filters__priority_level__contains="OVERSEAS")
    for saved_search in regional_saved_searches:
        new_priority_level = [each if each != "OVERSEAS" else "REGIONAL" for each in saved_search.filters["priority_level"]]
        saved_search.filters["priority_level"] = new_priority_level
        saved_search.save()

class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0153_auto_20230926_1034'),
    ]

    operations = [
        migrations.RunPython(update_saved_searches_to_overseas, update_saved_searches_to_regional),
    ]
