# Generated by Django 3.2.20 on 2023-11-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0154_auto_20230929_0956"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalbarrier",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical barrier",
                "verbose_name_plural": "historical barriers",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalbarriernextstepitem",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Barrier Next Step Item",
                "verbose_name_plural": "historical Barrier Next Step Items",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalbarrierprogressupdate",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Top 100 Barrier Progress Update",
                "verbose_name_plural": "historical Top 100 Barrier Progress Updates",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalbarrierreportstage",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical barrier report stage",
                "verbose_name_plural": "historical barrier report stages",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalbarriertopprioritysummary",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical barrier top priority summary",
                "verbose_name_plural": "historical barrier top priority summarys",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalprogrammefundprogressupdate",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Programme Fund Barrier Progress Update",
                "verbose_name_plural": "historical Programme Fund Barrier Progress Updates",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpublicbarrier",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical public barrier",
                "verbose_name_plural": "historical public barriers",
            },
        ),
        migrations.AlterField(
            model_name="historicalbarrier",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalbarriernextstepitem",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalbarrierprogressupdate",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalbarrierreportstage",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalbarriertopprioritysummary",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalprogrammefundprogressupdate",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalpublicbarrier",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
