# Generated by Django 3.2.23 on 2023-11-17 15:40

from django.db import migrations, models


def add_priority_level_pb100(apps, schema_editor):
    Barrier = apps.get_model("barriers", "Barrier")
    Barrier.objects.filter(
        priority_level="NONE", top_priority_status="APPROVED"
    ).update(priority_level="PB100")


def remove_priority_level_pb100(apps, schema_editor):
    Barrier = apps.get_model("barriers", "Barrier")
    Barrier.objects.filter(priority_level="PB100").update(priority_level="NONE")


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0155_auto_20231101_1613"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barrier",
            name="priority_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NONE", ""),
                    ("OVERSEAS", "Overseas Delivery"),
                    ("REGIONAL", "Regional Priority"),
                    ("COUNTRY", "Country Priority"),
                    ("WATCHLIST", "Watch list"),
                    ("PB100", "Top 100 Priority"),
                ],
                default="NONE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbarrier",
            name="priority_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NONE", ""),
                    ("OVERSEAS", "Overseas Delivery"),
                    ("REGIONAL", "Regional Priority"),
                    ("COUNTRY", "Country Priority"),
                    ("WATCHLIST", "Watch list"),
                    ("PB100", "Top 100 Priority"),
                ],
                default="NONE",
                max_length=20,
            ),
        ),
        migrations.RunPython(add_priority_level_pb100, remove_priority_level_pb100),
    ]
