# Generated by Django 3.2.23 on 2023-12-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0155_auto_20231101_1613"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barrier",
            name="top_priority_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NONE", ""),
                    ("APPROVAL_PENDING", "Top 100 Approval Pending"),
                    ("REMOVAL_PENDING", "Top 100 Removal Pending"),
                    ("APPROVED", "Top 100 Priority"),
                    ("RESOLVED", "Top 100 Priority Resolved"),
                ],
                default="NONE",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbarrier",
            name="top_priority_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NONE", ""),
                    ("APPROVAL_PENDING", "Top 100 Approval Pending"),
                    ("REMOVAL_PENDING", "Top 100 Removal Pending"),
                    ("APPROVED", "Top 100 Priority"),
                    ("RESOLVED", "Top 100 Priority Resolved"),
                ],
                default="NONE",
                max_length=50,
            ),
        ),
    ]
