# Generated by Django 3.2.20 on 2023-11-30 13:37

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models

class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0042_auto_20231122_1128'),
        ('barriers', '0155_auto_20231101_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBarrier_tags',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('barrier', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='barriers.barrier')),
                ('barriertag', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='metadata.barriertag')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='barriers.historicalbarrier')),
            ],
            options={
                'verbose_name': 'HistoricalBarrier_tags',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
