# Generated by Django 3.2.23 on 2024-01-10 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0157_auto_20231211_0728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpublicbarrier',
            old_name='changed_since_public',
            new_name='changed_since_published',
        ),
        migrations.RenameField(
            model_name='publicbarrier',
            old_name='changed_since_public',
            new_name='changed_since_published',
        ),
    ]
