# Generated by Django 4.2.10 on 2024-03-22 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0159_backfill_barrier_changed_since_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="barrier",
            options={
                "ordering": ["-reported_on"],
                "permissions": [
                    (
                        "change_barrier_public_eligibility",
                        "Can change barrier public eligibility",
                    )
                ],
            },
        ),
    ]
