# Generated by Django 4.2.7 on 2024-02-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0159_backfill_barrier_changed_since_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpublicbarrier",
            name="_public_view_status",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "Unknown"),
                    (10, "Not allowed"),
                    (20, "Allowed"),
                    (70, "Awaiting approval"),
                    (30, "Awaiting publishing"),
                    (40, "Published"),
                    (50, "Unpublished"),
                    (60, "Review later (Depricated)"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="publicbarrier",
            name="_public_view_status",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "Unknown"),
                    (10, "Not allowed"),
                    (20, "Allowed"),
                    (70, "Awaiting approval"),
                    (30, "Awaiting publishing"),
                    (40, "Published"),
                    (50, "Unpublished"),
                    (60, "Review later (Depricated)"),
                ],
                default=0,
            ),
        ),
    ]
