# Generated by Django 4.2.7 on 2024-02-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0161_recategorise_public_barriers__public_view_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpublicbarrier",
            name="approvers_summary",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="publicbarrier",
            name="approvers_summary",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
