# Generated by Django 4.2.7 on 2024-02-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0162_historicalpublicbarrier_approvers_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpublicbarrier",
            name="publishers_summary",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="publicbarrier",
            name="publishers_summary",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
