# Generated by Django 4.2.11 on 2024-06-24 11:12

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0166_set_to_allowed_on"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpublicbarrier",
            name="light_touch_reviews_cache",
        ),
        migrations.AddField(
            model_name="historicalpublicbarrier",
            name="main_sector",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalpublicbarrier",
            name="reported_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publicbarrier",
            name="main_sector",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publicbarrier",
            name="reported_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="PublicBarrierLightTouchReviews",
        ),
    ]
