# Generated by Django 4.2.14 on 2024-08-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0047_market_distorting_practices_tag"),
        ("barriers", "0169_alter_barrier_trading_bloc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="barrier",
            name="organisations_two",
            field=models.ManyToManyField(
                related_name="orgs", to="metadata.organisation"
            ),
        ),
    ]
