# Generated by Django 4.2.14 on 2024-08-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0048_policyteam"),
        ("barriers", "0169_alter_barrier_trading_bloc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="barrier",
            name="policy_teams",
            field=models.ManyToManyField(to="metadata.policyteam"),
        ),
    ]
