# Generated by Django 4.2.14 on 2024-08-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0169_alter_barrier_trading_bloc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="barrier",
            name="draft_test",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicalbarrier",
            name="draft_test",
            field=models.BooleanField(default=True),
        ),
    ]
