# Generated by Django 4.2.15 on 2024-08-27 13:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0170_historicalbarrierpolicyteam_barrierpolicyteam_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalbarrier",
            name="policy_teams_cache",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, default=list, size=None
            ),
        ),
    ]
