# Generated by Django 4.2.11 on 2024-10-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0171_historicalbarrier_policy_teams_cache"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barrier",
            name="trading_bloc",
            field=models.CharField(blank=True, choices=[], max_length=7),
        ),
        migrations.AlterField(
            model_name="historicalbarrier",
            name="trading_bloc",
            field=models.CharField(blank=True, choices=[], max_length=7),
        ),
    ]
