# Generated by Django 4.2.18 on 2025-02-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barriers", "0173_historicalestimatedresolutiondaterequest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimatedresolutiondaterequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEEDS_REVIEW", "Needs Review"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="NEEDS_REVIEW",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalestimatedresolutiondaterequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEEDS_REVIEW", "Needs Review"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="NEEDS_REVIEW",
            ),
            preserve_default=False,
        ),
    ]
