# Generated by Django 3.2.15 on 2022-08-25 12:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfaction', models.CharField(blank=True, choices=[('NONE', ''), ('VERY_SATISFIED', 'Very satisfied'), ('SATISFIED', 'Satisfied'), ('NEITHER', 'Neither satisfied nor dissatisfied'), ('DISSATISFIED', 'Dissatisfied'), ('VERY_DISSATISFIED', 'Very dissatisfied')], default='NONE', max_length=40)),
                ('attempted_actions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None)),
                ('feedback_text', models.TextField(blank=True, default='')),
            ],
        ),
    ]
