# Generated by Django 3.2.13 on 2022-08-31 09:00

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="created_on",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
