# Generated by Django 3.2.20 on 2023-09-18 15:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_feedback_created_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="experienced_issues",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=30),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
