# Generated by Django 3.2.23 on 2023-12-07 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_rename_assessment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CachedHistoryItem',
        ),
    ]
