# Generated by Django 2.0.5 on 2018-07-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barriertype',
            name='is_goods',
        ),
        migrations.AddField(
            model_name='barriertype',
            name='category',
            field=models.CharField(choices=[('GOODS', 'GOODS'), ('Goods', 'Goods'), (
                'SERVICES', 'SERVICES'), ('Services', 'Services')], max_length=20),
        ),
    ]
