# Generated by Django 2.0.5 on 2018-07-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barriertype',
            old_name='is_goods',
            new_name='category',
        ),
        migrations.AddField(
            model_name='barriertype',
            name='status',
            field=models.CharField(choices=[('GOODS', 'GOODS'), ('Goods', 'Goods'), ('SERVICES', 'SERVICES'), ('Services', 'Services')], max_length=20, null=True),
        ),
    ]
