# Generated by Django 2.0.5 on 2018-09-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("metadata", "0005_auto_20180806_1630")]

    operations = [
        migrations.AlterField(
            model_name="barriertype",
            name="category",
            field=models.CharField(
                choices=[
                    ("GOODS", "Goods"),
                    ("SERVICES", "Services"),
                    ("GOODSANDSERVICES", "Goods and Services"),
                ],
                max_length=20,
            ),
        )
    ]
