# Generated by Django 2.2.10 on 2020-03-18 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0040_auto_20200318_1036'),
        ('metadata', '0011_auto_20190903_1006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BarrierType',
            new_name='Category',
        ),
    ]
