# Generated by Django 2.2.4 on 2019-09-19 11:09
import logging

logger = logging.getLogger(__name__)

from django.db import migrations

def remove_duplicate_barrier(apps, schema_editor):

    BarrierInstance = apps.get_model("barriers", "BarrierInstance")

    uuid = "8b4fa045-3c3e-44c6-bfa9-9a213e3ff27e"

    try:
        barrier_to_delete = BarrierInstance.objects.get(id=uuid)
        
        # delete related fields first
        barrier_to_delete.assessment.delete()
        
        barrier_to_delete.progress.all().delete()

        barrier_to_delete.barrier_team.all().delete()

        barrier_to_delete.interactions_documents.all().delete()

        barrier_to_delete.delete()

    except BarrierInstance.DoesNotExist:
        # We don't care if the barrier isn't found
        logger.info("Nothing to do! Barrier with uuid %s was not found", uuid)


def fake_down(apps, schema_editor):
    logger.info("This doesn't actually do anything")


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0011_auto_20190903_1006'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_barrier, fake_down),
    ]
