# Generated by Django 2.2.4 on 2019-09-19 11:09
import logging

logger = logging.getLogger(__name__)

from django.db import migrations

def remove_duplicate_barrier(apps, schema_editor):

    BarrierInstance = apps.get_model("barriers", "BarrierInstance")

    uuid = "9fad3fd0-8890-4684-9cb2-c17c80e07247"

    try:
        barrier_to_delete = BarrierInstance.objects.get(id=uuid)
        print(barrier_to_delete)
    except BarrierInstance.DoesNotExist:
        # We don't care if the barrier isn't found
        logger.info("Barrier with uuid %s was not found", uuid)

    raise Exception('not implemented exception csharp luvvies')


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0011_auto_20190903_1006'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_barrier),
    ]
