# Generated by Django 3.1.2 on 2020-11-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0015_nip_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('organisation_type', models.IntegerField(choices=[(1, 'Ministerial departments'), (2, 'Devolved administrations')])),
            ],
        ),
    ]
