# Generated by Django 3.1.2 on 2020-11-18 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0017_add_gov_organisations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='organisation',
            unique_together={('name', 'organisation_type')},
        ),
    ]
