# Generated by Django 3.2.12 on 2022-02-21 10:21

from django.db import migrations

# create new Category with title of "Import controls" a description of "" and category of "GOODS"
def add_import_controls_category(apps, schema_editor):
    Category = apps.get_model("metadata", "Category")
    Category.objects.get_or_create(
        title="Import controls", defaults={"description": "", "category": "GOODS"}
    )

class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0020_add_more_organisations'),
    ]

    operations = [
        migrations.RunPython(add_import_controls_category, migrations.RunPython.noop)
    ]
