# Generated by Django 3.2.7 on 2022-03-18 15:11

from django.db import migrations


def rename_top_priority_barrier(apps, schema_editor):
    # rename BarrierTag with title 'TOP-PRIORITY BARRIER' to 'TOP 100 PRIORITY BARRIER'
    BarrierTag = apps.get_model("metadata", "BarrierTag")
    BarrierTag.objects.filter(title="TOP-PRIORITY BARRIER").update(
        title="TOP 100 PRIORITY BARRIER"
    )


def reverse_rename_top_priority_barrier(apps, schema_editor):
    # rename BarrierTag with title 'TOP 100 PRIORITY BARRIER' to 'TOP-PRIORITY BARRIER'
    BarrierTag = apps.get_model("metadata", "BarrierTag")
    BarrierTag.objects.filter(title="TOP 100 PRIORITY BARRIER").update(
        title="TOP-PRIORITY BARRIER"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0022_top_priority_tag"),
    ]

    operations = [
        migrations.RunPython(
            rename_top_priority_barrier,
            reverse_code=reverse_rename_top_priority_barrier,
        ),
    ]
