# Generated by Django 3.2.13 on 2022-06-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0024_barriertag_is_top_priority_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barriertag",
            name="title",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
