# Generated by Django 3.2.13 on 2022-06-28 15:22

from django.db import migrations


ASIA_PACIFIC_TAG = {
    "Asia Pacific Cross-Government Pilot": {
        "description": "",
        "order": 4,
        "show_at_reporting": True,
    },
}


def create_asia_pacific_tag(apps, schema_editor):
    BarrierTag = apps.get_model("metadata", "BarrierTag")

    title, defaults = ASIA_PACIFIC_TAG.popitem()
    BarrierTag.objects.update_or_create(
        title=title,
        defaults=defaults,
    )


def destroy_asia_pacific_tag(apps, schema_editor):
    BarrierTag = apps.get_model("metadata", "BarrierTag")

    title, _ = ASIA_PACIFIC_TAG.popitem()
    BarrierTag.objects.filter(title=title).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0025_alter_barriertag_title"),
    ]

    operations = [
        migrations.RunPython(
            create_asia_pacific_tag, reverse_code=destroy_asia_pacific_tag
        ),
    ]
