# Generated by Django 3.2.15 on 2022-09-28 10:04

from django.db import migrations

REGIONAL_TRADE_PLAN = {
    "Regional Trade Plan": {
        "description": "",
        "order": 6,
        "show_at_reporting": True,
    },
}


def create_regional_trade_plan(apps, schema_editor):
    BarrierTag = apps.get_model("metadata", "BarrierTag")

    title, defaults = REGIONAL_TRADE_PLAN.popitem()
    BarrierTag.objects.update_or_create(
        title=title,
        defaults=defaults,
    )


def destroy_regional_trade_plan(apps, schema_editor):
    BarrierTag = apps.get_model("metadata", "BarrierTag")

    title, _ = REGIONAL_TRADE_PLAN.popitem()
    BarrierTag.objects.filter(title=title).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0029_clean_growth_tag"),
    ]

    operations = [
        migrations.RunPython(
            create_regional_trade_plan, reverse_code=destroy_regional_trade_plan
        ),
    ]
