# Generated by Django 3.2.19 on 2023-06-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0033_add_eu_market_access_board_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
