# Generated by Django 3.2.20 on 2023-09-05 19:15

from django.db import migrations

def create_scoping_tag(apps, schema_editor):
    BarrierTag = apps.get_model("metadata", "BarrierTag")
    BarrierTag.objects.create(
        order=12,
        title="Scoping",
        show_at_reporting=True,
        id=12,
    )

def delete_scoping_tag(apps, schema_editor):
    BarrierTag = apps.get_model("metadata", "BarrierTag")
    BarrierTag.objects.filter(title="Scoping").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0037_add_wales_priority_tag'),
    ]

    operations = [
        migrations.RunPython(create_scoping_tag, delete_scoping_tag)
    ]
