# Generated by Django 3.2.20 on 2023-09-26 15:38

from django.db import migrations

def change_tag_ordering(apps, schema_editor):
    BarrierTag = apps.get_model("metadata", "BarrierTag")

    scoping_tag = BarrierTag.objects.get(title="Scoping (Top 100 priority barrier)")
    scoping_tag.order = 1
    scoping_tag.save()

    for tag in BarrierTag.objects.exclude(id=scoping_tag.id).order_by("order"):
        tag.order += 1
        tag.save()

class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0038_auto_20230907_1018'),
    ]

    operations = [
        migrations.RunPython(change_tag_ordering),
    ]
