# Generated by Django 3.2.20 on 2023-10-11 10:11

from django.db import migrations

new_tag_name = "EU Priority"

def create_tag(apps, schema_editor):
    BarrierTag = apps.get_model("metadata", "BarrierTag")
    BarrierTag.objects.create(
        order=12,
        title=new_tag_name,
        show_at_reporting=True,
    )

def delete_tag(apps, schema_editor):
    BarrierTag = apps.get_model("metadata", "BarrierTag")
    BarrierTag.objects.filter(title=new_tag_name).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0039_auto_20230926_1538'),
    ]

    operations = [
        migrations.RunPython(create_tag, delete_tag)
    ]
