# Generated by Django 3.2.20 on 2023-10-31 16:26

from django.db import migrations

old_tag_title = "EU Priority"
new_tag_title = "Europe Priority"

def rename_eu_priority_tag(apps, schema_editor):
    BarrierTag = apps.get_model("metadata", "BarrierTag")
    BarrierTag.objects.filter(title=old_tag_title).update(title=new_tag_title)

def reverse_rename_eu_priority_tag(apps, schema_editor):
    BarrierTag = apps.get_model("metadata", "BarrierTag")
    BarrierTag.objects.filter(title=new_tag_title).update(title=old_tag_title)

class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0040_auto_20231011_1011'),
    ]

    operations = [
        migrations.RunPython(rename_eu_priority_tag, reverse_rename_eu_priority_tag),
    ]
