# Generated by Django 3.2.23 on 2023-11-22 11:28

from django.db import migrations


def remove_asia_pacific_pilot_tags(apps, schema_editor):
    BarrierTag = apps.get_model("metadata", "BarrierTag")
    BarrierTag.objects.filter(title="Asia Pacific Pilot").delete()


def create_asia_pacific_pilot_tag(apps, schema_editor):
    BarrierTag = apps.get_model("metadata", "BarrierTag")
    BarrierTag.objects.create(title="Asia Pacific Pilot")


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0041_auto_20231031_1626"),
        ("user", "0033_auto_20231122_1312"),
    ]

    operations = [
        migrations.RunPython(
            remove_asia_pacific_pilot_tags,
            create_asia_pacific_pilot_tag,
        ),
    ]
