# Generated by Django 3.2.20 on 2023-11-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0042_auto_20231122_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='barriertag',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
