# Generated by Django 3.2.20 on 2023-11-30 14:03

from django.db import migrations

def back_fill_historical_barrier_tags(apps, schema_editor):
    Barrier = apps.get_model("barriers", "Barrier")
    BarrierTag = apps.get_model("metadata", "BarrierTag")
    HistoricalBarrier = apps.get_model("barriers", "HistoricalBarrier")
    HistoricalBarrierTag = apps.get_model("barriers", "HistoricalBarrier_tags")

    for barrier_object in Barrier.objects.filter(tags__isnull=False):
        historical_records = HistoricalBarrier.objects.filter(id=barrier_object.id)
        for record in historical_records:
            if record.tags_cache == record.previous_record.tags_cache:
                continue  # no change in tags
            else:
                # we need to find out here what tags have been added or removed from the barrier
                difference = set(record.tags_cache) - set(record.previous_record.tags_cache)
                if difference:
                    # tags have been added
                    for tag_object in BarrierTag.objects.filter(id__in=difference):
                        HistoricalBarrierTag.objects.create(
                            barrier_id=barrier_object.id,
                            barriertag_id=tag_object.id,
                            history_date=record.history_date,
                            history_user=record.history_user,
                            history_type="+",
                        )
                else:
                    difference = set(record.previous_record.tags_cache) - set(record.tags_cache)
                    # tags have been removed
                    for tag_object in BarrierTag.objects.filter(id__in=difference):
                        HistoricalBarrierTag.objects.create(
                            barrier_id=barrier_object.id,
                            barriertag_id=tag_object.id,
                            history_date=record.history_date,
                            history_user=record.history_user,
                            history_type="-",
                        )


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0042_auto_20231122_1128'),
        ('barriers', '0156_historicalbarrier_tags'),
    ]

    operations = [
        migrations.RunPython(back_fill_historical_barrier_tags),
    ]
