# Generated by Django 3.2.20 on 2023-12-04 15:30

from django.db import migrations
from django.db.models import Q


def remove_ni_protocol_and_brexit_tags(apps, schema_editor):
    """Removing Brexit/NI Protocol tags from saved searches"""
    BarrierTag = apps.get_model("metadata", "BarrierTag")
    SavedSearch = apps.get_model("user", "SavedSearch")

    brexit_tag = BarrierTag.objects.get(title="Brexit")
    ni_protocol_tag = BarrierTag.objects.get(title="NI Protocol")
    saved_searches = SavedSearch.objects.filter(
        Q(filters__tags__contains=brexit_tag.id)
        | Q(filters__tags__contains=ni_protocol_tag.id)
    )
    for search in saved_searches:
        search.filters["tags"].remove(brexit_tag.id)
        search.filters["tags"].remove(ni_protocol_tag.id)
        search.save()


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0042_auto_20231122_1128"),
    ]

    operations = [
        migrations.RunPython(
            remove_ni_protocol_and_brexit_tags,
        ),
    ]
