# Generated by Django 3.2.20 on 2023-11-29 20:27

from django.db import migrations

from api.metadata.migrations import remove_tag_wrapper

def create_brexit_tag(apps, schema_editor):
    BarrierTag = apps.get_model("metadata", "BarrierTag")
    BarrierTag.objects.create(title="Brexit", order=2)



class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0043_barriertag_archived'),
    ]

    operations = [
        migrations.RunPython(
            remove_tag_wrapper("Brexit"),
            reverse_code=create_brexit_tag
        ),
    ]
