# Generated by Django 3.2.15 on 2022-09-28 10:04

from django.db import migrations

REGULATOR = {
    "Programme Fund - Regulator": {
        "description": "",
        "show_at_reporting": True,
    },
}

REGIONAL = {
    "Programme Fund - Facilitative Regional": {
        "description": "",
        "show_at_reporting": True,
    },
}


def create_new_tags(apps, schema_editor):
    BarrierTag = apps.get_model("metadata", "BarrierTag")

    order = BarrierTag.objects.order_by('-order')[:1].get().order

    for tag in [REGIONAL, REGULATOR]:
        order += 1
        title, defaults = tag.popitem()
        BarrierTag.objects.create(
            title=title,
            order=order,
            **defaults
        )


def destroy_new_tags(apps, schema_editor):
    BarrierTag = apps.get_model("metadata", "BarrierTag")

    for tag in [REGIONAL, REGULATOR]:
        title, _ = tag.popitem()
        BarrierTag.objects.filter(title=title).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0044_auto_20231204_1536"),
    ]

    operations = [
        migrations.RunPython(
            create_new_tags, reverse_code=destroy_new_tags
        ),
    ]
