# Generated by Django 4.2.11 on 2024-06-07 08:12

from django.db import migrations


def remove_brexit_and_nip_tags(apps, schema_editor):
    """Removing Brexit and NIP tags to avoid confusion to users because they are no longer relevant."""
    BarrierTag = apps.get_model("metadata", "BarrierTag")

    BarrierTag.objects.filter(title="Brexit").delete()
    BarrierTag.objects.filter(title="NI Protocol").delete()


def create_brexit_and_nip_tags(apps, schema_editor):
    """Creating Brexit and NIP tags."""
    BarrierTag = apps.get_model("metadata", "BarrierTag")

    BarrierTag.objects.create(title="Brexit")
    BarrierTag.objects.create(title="NI Protocol")


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0045_programme_fund_tags"),
    ]

    operations = [
        migrations.RunPython(
            remove_brexit_and_nip_tags, reverse_code=create_brexit_and_nip_tags
        ),
    ]
