# Generated by Django 4.2.11 on 2024-06-07 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0045_programme_fund_tags"),
    ]

    operations = []
