# Generated by Django 4.2.11 on 2024-06-18 10:43

from django.db import migrations

MARKET_DISTORTING_PRACTICES_TAG = {
    "title": "Market Distorting Practices (MDP)",
    "description": "",
    "show_at_reporting": True,
}


def create_market_distorting_practices_tag(apps, schema_editor):
    BarrierTag = apps.get_model("metadata", "BarrierTag")

    order = BarrierTag.objects.order_by("-order")[:1].get().order
    order += 1

    BarrierTag.objects.create(order=order, **MARKET_DISTORTING_PRACTICES_TAG)


def destroy_market_distorting_practices_tag(apps, schema_editor):
    BarrierTag = apps.get_model("metadata", "BarrierTag")

    title, _ = MARKET_DISTORTING_PRACTICES_TAG.popitem()
    BarrierTag.objects.filter(title=title).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0046_auto_20240607_0812"),
    ]

    operations = [
        migrations.RunPython(
            create_market_distorting_practices_tag,
            reverse_code=destroy_market_distorting_practices_tag,
        ),
    ]
