# Generated by Django 4.2.21 on 2025-05-29 11:28

from django.db import migrations

INNOVATION_TEAM = {
    "pk": 18,
    "title": "Innovation Trade Policy",
    "description": "The Innovation Trade Policy team helps UK businesses export innovative goods and services. They do this by horizon-scanning for potential trade barriers and opportunities within priority sectors, with a focus on emerging technologies. Potential barriers may include differing market standards on future technologies."
}


def create_innovation_team(apps, schema_editor):
    PolicyTeam = apps.get_model("metadata", "PolicyTeam")
    PolicyTeam.objects.update_or_create(**INNOVATION_TEAM)


def destroy_innovation_team(apps, schema_editor):
    PolicyTeam = apps.get_model("metadata", "PolicyTeam")
    PolicyTeam.objects.filter(pk=INNOVATION_TEAM["pk"]).delete()



class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0050_market_shaping_tag"),
    ]

    operations = [
        migrations.RunPython(
            create_innovation_team,
            reverse_code=destroy_innovation_team,
        ),
    ]
