# Generated by Django 2.2.11 on 2020-04-20 15:32

from django.db import migrations


def create_committee_groups(apps, schema_editor):
    WTOCommitteeGroup = apps.get_model('wto', 'WTOCommitteeGroup')

    committee_groups = [
        {
            "pk": "0a8b978c-efaa-427f-bcaa-18021b3be424",
            "name": "General Council and bodies reporting to it"
        }, {
            "pk": "2cb189d4-b57f-4869-b7e3-4d898b637b6b",
            "name": "Committees of Plurilateral Agreements"
        }, {
            "pk": "33049400-2811-418a-863b-2de59f254bda",
            "name": "Bodies established under the Trade Negotiations Committee"
        }, {
            "pk": "5aeb6715-d472-4a1b-8498-f3e44a877ca4",
            "name": "Subsidiary bodies of the Council for Trade in Services"
        }, {
            "pk": "f2db8548-64cf-4c2c-82d0-4d6f8fb35e26",
            "name": "Subsidiary bodies of the Council for Trade in Goods"
        }
    ]

    WTOCommitteeGroup.objects.bulk_create([
        WTOCommitteeGroup(**committee_group) for committee_group in committee_groups
    ])


def create_committees(apps, schema_editor):
    WTOCommittee = apps.get_model('wto', 'WTOCommittee')

    committees = [

    ]

    WTOCommittee.objects.bulk_create([
        WTOCommittee(**committee) for committee in committees
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('wto', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_committee_groups,
            create_committees,
            reverse_code=migrations.RunPython.noop
        ),
    ]
