# Generated by Django 2.2.11 on 2020-04-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wto", "0002_auto_20200420_1532"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalwtoprofile",
            name="committee_notification_link",
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name="wtoprofile",
            name="committee_notification_link",
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
