# Generated by Django 2.2.13 on 2020-08-12 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0081_auto_20200812_0815'),
        ('wto', '0003_auto_20200429_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwtoprofile',
            name='barrier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='barriers.BarrierInstance'),
        ),
        migrations.AddField(
            model_name='wtoprofile',
            name='barrier',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='barriers.BarrierInstance'),
        ),
    ]
