# Generated by Django 2.2.13 on 2020-08-12 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wto', '0005_copy_onetoonefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wtoprofile',
            name='barrier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wto_profile', to='barriers.BarrierInstance'),
        ),
    ]
