# Generated by Django 3.1.2 on 2020-11-05 17:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wto", "0008_convert_null_to_empty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalwtoprofile",
            name="member_states",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(), blank=True, default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="wtoprofile",
            name="member_states",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(), blank=True, default=list, size=None
            ),
        ),
    ]
