# Generated by Django 3.2.20 on 2023-10-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wto', '0009_fix_blank_and_null'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalwtoprofile',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical wto profile', 'verbose_name_plural': 'historical wto profiles'},
        ),
        migrations.AlterField(
            model_name='historicalwtoprofile',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
