# Generated by Django 2.2.13 on 2020-07-16 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('suffix', models.CharField(max_length=2)),
                ('description', models.TextField()),
                ('level', models.IntegerField()),
                ('indent', models.IntegerField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commodities.Commodity')),
            ],
        ),
    ]
