# Generated by Django 2.2.13 on 2020-07-22 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=10)),
                ('suffix', models.CharField(max_length=2)),
                ('description', models.TextField()),
                ('level', models.IntegerField()),
                ('indent', models.IntegerField()),
                ('is_leaf', models.BooleanField(default=False)),
                ('sid', models.IntegerField()),
                ('parent_sid', models.IntegerField(null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commodities.Commodity')),
            ],
        ),
    ]
