# Generated by Django 3.2.7 on 2021-10-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0002_auto_20200723_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='classification',
            field=models.CharField(default='H5', max_length=10),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='indent',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='sid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='suffix',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
