# Generated by Django 4.2.20 on 2025-05-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0002_auto_20200723_1020"),
    ]

    operations = [
        migrations.AddField(
            model_name="commodity",
            name="parent_code",
            field=models.IntegerField(null=True),
        ),
    ]
