# Generated by Django 4.2.20 on 2025-05-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0003_commodity_parent_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commodity",
            name="sid",
            field=models.IntegerField(null=True),
        ),
    ]
