# Generated by Django 4.2.21 on 2025-05-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0004_alter_commodity_sid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commodity",
            name="parent_code",
            field=models.CharField(null=True),
        ),
    ]
