# Generated by Django 4.2.21 on 2025-05-29 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commodities", "0005_alter_commodity_parent_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commodity",
            options={"verbose_name_plural": "commodities"},
        ),
    ]
