# Generated by Django 3.1.1 on 2020-09-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="av_clean",
            field=models.BooleanField(db_index=True, null=True),
        ),
    ]
