# Generated by Django 3.1.2 on 2020-10-14 13:52

from django.db import migrations


def update_default_to_documents(apps, schema_editor):
    Document = apps.get_model("documents", "Document")
    Document.objects.filter(bucket_id="default").update(bucket_id="documents")


def update_documents_to_default(apps, schema_editor):
    Document = apps.get_model("documents", "Document")
    Document.objects.filter(bucket_id="documents").update(bucket_id="default")


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20200901_1511'),
    ]

    operations = [
        migrations.RunPython(update_default_to_documents, reverse_code=update_documents_to_default),
    ]
