# Generated by Django 2.1.5 on 2019-03-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_auto_20190308_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='detached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='detached',
            field=models.BooleanField(default=False),
        ),
    ]
