# Generated by Django 2.2.10 on 2020-03-19 15:53

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_auto_20190322_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinteraction',
            name='documents_cache',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), blank=True, default=None, null=True, size=None),
        ),
    ]
