# Generated by Django 2.2.8 on 2019-12-12 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_auto_20190322_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='barrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_documents', to='barriers.BarrierInstance'),
        ),
    ]
