# Generated by Django 2.2.10 on 2020-03-20 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_historicalinteraction_documents_cache'),
    ]

    operations = [
    ]
