# Generated by Django 2.2.10 on 2020-03-26 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0004_auto_20191212_1542"),
        ("interactions", "0006_populate_documents_history"),
    ]

    operations = []
