# Generated by Django 3.1.1 on 2020-09-01 15:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0008_historicalpublicbarriernote_publicbarriernote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalinteraction",
            name="documents_cache",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
