# Generated by Django 3.1.7 on 2021-03-12 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("interactions", "0013_mention_email_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="mention",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="mention",
            name="object_id",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="mention",
            name="read_by_recipient",
            field=models.BooleanField(default=False),
        ),
    ]
