# Generated by Django 3.1.7 on 2021-03-12 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0014_auto_20210312_0118"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mention",
            options={"ordering": ["-created_on"]},
        ),
    ]
