# Generated by Django 3.1.7 on 2021-03-15 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("interactions", "0016_excludefromnotifcation"),
    ]

    operations = [
        migrations.AddField(
            model_name="mention",
            name="text",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="excludefromnotifcation",
            name="excluded_user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="excluded_notification",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
