# Generated by Django 3.1.7 on 2021-03-23 11:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("interactions", "0017_auto_20210315_1721"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ExcludeFromNotifcation",
            new_name="ExcludeFromNotifications",
        ),
    ]
