# Generated by Django 3.1.7 on 2021-03-29 17:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("interactions", "0018_auto_20210323_1117"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ExcludeFromNotifications",
            new_name="ExcludeFromNotification",
        ),
    ]
